In [37]:
import pandas as pd
import matplotlib.pyplot as plt

pd.set_option('display.max_columns', None)

In [20]:
df_TX = pd.read_csv('data/final_mergedDF_TX.csv', low_memory=False)
df_TX

,Beneficiary_ID,Assessment_Effective_Date,Submitted_HIPPS_Code,Facility_Internal_ID,Age,Gender,American_Indian_or_Alaska_Native,Asian,Black_or_African_American,Hispanic_or_Latino,Native_Hawiian_or_Pacific_Islander,White,ByDiscipline,Days_Cared_For,Agency_Medicare_Number,has_diabetes,has_heart_failure,has_hypertension,ever_deceased,ever_readmitted,BMI,BMI_Category,charlson_score,charlson_ageadj,charlson_survival_10yr,elix_quan_score,elix_quan_ageadj,elix_swiss_score,elix_swiss_ageadj,aids,alcohol,ami,blane,canc,carit,cevd,chf,coag,copd,dane,dementia,depre,diab,diabc,diabunc,diabwc,drug,fed,hp,hypc,hypothy,hypunc,ld,lymph,metacanc,msld,obes,ond,pcd,psycho,pud,pvd,rend,rheumd,valv,wloss,Primary_Diagnosis_ICD_10_C_M_Code_Cluster,Primary_Diagnosis_ICD_10_C_M_Code_Cluster_Name,Other_Diagnosis_Code_1_ICD_10_C_M_Cluster,Other_Diagnosis_Code_1_ICD_10_C_M_Cluster_Name,Other_Diagnosis_Code_2_ICD_10_C_M_Cluster,Other_Diagnosis_Code_2_ICD_10_C_M_Cluster_Name,Other_Diagnosis_Code_3_ICD_10_C_M_Cluster,Other_Diagnosis_Code_3_ICD_10_C_M_Cluster_Name,Other_Diagnosis_Code_4_ICD_10_C_M_Cluster,Other_Diagnosis_Code_4_ICD_10_C_M_Cluster_Name,Other_Diagnosis_Code_5_ICD_10_C_M_Cluster,Other_Diagnosis_Code_5_ICD_10_C_M_Cluster_Name,ICD_Clusters_In_Row,ICD_Cluster_Names_In_Row,zip,state_id,city,state_name,COUNTY_NAME,POP_URB,POPPCT_URB,POP_RUR,POPPCT_RUR,COUNTYFIPS,ACS_PCT_BACHELOR_DGR,ACS_PCT_COLLEGE_ASSOCIATE_DGR,ACS_PCT_GRADUATE_DGR,ACS_PCT_HS_GRADUATE,ACS_PCT_LT_HS,ACS_PCT_NO_WORK_NO_SCHL_16_19,ACS_PCT_POSTHS_ED,ACS_PCT_VET_BACHELOR,ACS_PCT_VET_COLLEGE,ACS_PCT_VET_HS,ACS_PCT_HH_LIMIT_ENGLISH,ACS_PCT_HH_BROADBAND,ACS_PCT_HH_BROADBAND_ONLY,ACS_PCT_HH_CELLULAR,ACS_PCT_HH_CELLULAR_ONLY,ACS_PCT_HH_DIAL_INTERNET_ONLY,ACS_PCT_HH_INTERNET,ACS_PCT_HH_INTERNET_NO_SUBS,ACS_PCT_HH_NO_COMP_DEV,ACS_PCT_HH_NO_INTERNET,ACS_PCT_HH_OTHER_COMP,ACS_PCT_HH_OTHER_COMP_ONLY,ACS_PCT_HH_PC,ACS_PCT_HH_PC_ONLY,ACS_PCT_HH_SAT_INTERNET,ACS_PCT_HH_SMARTPHONE,ACS_PCT_HH_SMARTPHONE_ONLY,ACS_PCT_HH_TABLET,ACS_PCT_HH_TABLET_ONLY,ACS_PCT_CHILDREN_GRANDPARENT,ACS_PCT_CHILD_1FAM,ACS_PCT_GRANDP_NO_RESPS,ACS_PCT_GRANDP_RESPS_NO_P,ACS_PCT_GRANDP_RESPS_P,ACS_PCT_HH_1PERS,ACS_PCT_HH_ABOVE65,ACS_PCT_HH_ALONE_ABOVE65,ACS_PCT_HH_KID_1PRNT,ACS_TOT_GRANDCHILDREN_GP,ACS_PCT_HEALTH_INC_138_199,ACS_PCT_HEALTH_INC_200_399,ACS_PCT_HEALTH_INC_ABOVE400,ACS_PCT_HEALTH_INC_BELOW137,ACS_PCT_HH_1FAM_FOOD_STMP,ACS_PCT_HH_FOOD_STMP_BLW_POV,ACS_PCT_HH_NO_FD_STMP_BLW_POV,ACS_PCT_HH_PUB_ASSIST,ACS_PCT_INC50,ACS_PCT_INC50_ABOVE65,ACS_PCT_NONVET_POV_18_64,ACS_PCT_PERSON_INC_100_124,ACS_PCT_PERSON_INC_125_199,ACS_PCT_PERSON_INC_ABOVE200,ACS_PCT_PERSON_INC_BELOW99,ACS_PCT_POV_AIAN,ACS_PCT_POV_ASIAN,ACS_PCT_POV_BLACK,ACS_PCT_POV_HISPANIC,ACS_PCT_POV_MULTI,ACS_PCT_POV_NHPI,ACS_PCT_POV_OTHER,ACS_PCT_POV_WHITE,ACS_PCT_VET_POV_18_64,ACS_TOT_POP_POV
0,GGGGGGG99DzGeze,2017-03-17,1AGKU,334582,46,Female,0,0,1,0,0,0,RN,25,677994,0,0,0,1,1,29.898299,Overweight,4.0,4.0,0.533915,9.0,9.0,18.0,18.0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,-1,Isolated / Unclustered,-141,"Symptoms/Signs: R10.11, R10.31",2,Genitourinary: N18.5,-1,Isolated / Unclustered,26,"Factors Influencing Health Status: Z45.2, Z79.2",0,"Circulatory: I10., M62.81","[-141, 0, 2, 26]","['Circulatory: I10., M62.81', 'Factors Influen...",77037,TX,Houston,Texas,Harris,974.0,2.81,33694.0,97.19,13145.0,18.742857,36.044286,13.007143,25.427143,6.781429,1.932857,67.791429,34.930000,43.618571,21.450000,0.141429,67.004286,7.255714,75.972857,12.107143,0.292857,85.781429,1.478571,5.607143,12.738571,2.675714,0.000000,81.012857,4.245714,9.700000,86.352857,9.494286,68.822857,0.477143,9.277143,17.435714,40.381429,18.250000,41.368571,18.477143,33.230000,8.747143,11.338571,91.571429,9.890000,32.284286,47.674286,10.150000,25.710000,2.957143,2.585714,7.870000,3.257143,1.658571,5.768571,2.601429,11.638571,79.958571,5.800000,0.000000,2.844286,5.634286,3.997143,6.295714,0.000000,0.000000,5.320000,0.817143,4868.571429
1,GGGGGGG9DDWNGGz,2017-02-28,2CGKU,487590,74,Female,0,0,0,0,0,1,RN,54,679724,0,0,0,1,0,33.197222,Obese-Class1,1.0,4.0,0.533915,3.0,6.0,0.0,3.0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,"Circulatory: I10., M62.81",-1,Isolated / Unclustered,-1,Isolated / Unclustered,0,"Circulatory: I10., M62.81",0,"Circulatory: I10., M62.81",15,"Endocrine/Metabolic: E78.5, E03.9","[0, 15]","['Circulatory: I10., M62.81', 'Endocrine/Metab...",75044,TX,Garland,Texas,Dallas,21207.0,55.14,17255.0,44.86,1047.0,10.545294,31.229412,5.929412,35.907647,16.389412,6.047059,47.703529,12.586471,47.370588,40.040588,0.166471,41.618824,6.047059,62.783529,19.321176,0.419412,71.655294,1.708235,24.328824,26.637059,0.706471,0.000000,52.237059,5.984118,10.360588,65.979412,17.080588,39.018235,1.327059,20.106471,63.601765,38.752353,14.840588,46.407647,37.265294,35.581765,16.677647,26.692941,114.235294,13.866471,28.326471,19.230588,38.575882,53.601176,16.195294,8.889412,29.968824,10.930000,3.444706,23.831176,7.732353,17.348824,47.557647,27.362353,13.445294,0.000000,31.530000,8.717059,7.271176,0.000000,5.882353,13.491176,18.041176,2209.294118
2,GGGGGGG9DDWWeeX,2017-10-22,1CHKS,63847,75,Male,0,0,0,0,0,1,RN,37,679236,0,0,0,1,0,27.194009,Overweight,1.0,4.0,0.533915,0.0,3.0,0.0,3.0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,4,"Factors Influencing Health Status: Z48.812, I21.4",-1,Isolated / Unclustered,-1,Isolated / Unclustered,0,"Circulatory: I10., M62.81",0,"Circulatory: I10., M62.81",21,Mental/Behavioral: F03.90,"[0, 4, 21]","['Circulatory: I10., M62.81', 'Factors Influen...",75070,TX,Mckinney,Texas,Collin,999005.0,93.85,65460.0,6.15,48085.0,33.544045,26.076091,19.293682,14.445273,6.186000,0.708045,78.914227,47.769182,35.078682,15.788318,4.921545,83.973455,8.104000,84.431545,6.473273,0.072636,93.578818,1.297773,1.709727,4.669455,4.171000,0.042864,90.940864,2.370727,7.718545,93.952591,4.400864,74.761636,0.326227,3.902545,20.265091,34.616136,12.416045,20.240682,21.790864,21.080136,6.321000,12.976727,45.881818,6.623636,23.725682,58.459455,10.736455,7.268955,0.904455,5.726818,3.434955,3.960545,4.068682,6.547545,2.374818,7.981318,82.184273,7.004545,4.326727,8.702818,8.223818,8.853182,7.923045,1.074364,7.404455,5.317909,4.171409,4546.331818
3,GGGGGGG9DGXzUSG,2017-09-13,1BHKT,10206,75,Male,0,0,0,0,0,1,RN,57,677247,0,0,0,0,0,22.594123,Normal weight,0.0,3.0,0.774816,0.0,3.0,0.0,3.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-1,Isolated / Unclustered,26,"Factors Influencing Health Status: Z45.2, Z79.2",0,"Circulatory: I10., M62.81",-108,"Musculoskeletal: M21.371, M21.372",-108,"Musculoskeletal: M21.371, M21.372",-1,Isolated / Unclustered,"[-108, 0, 26]","['Circulatory: I10., M62.81', 'Factors Influen...",77975,TX,Moulton,Texas,Lavaca,3582.0,17.61,16755.0,82.39,48285.0,12.981667,28.170000,4.646667,40.461667,13.740000,4.688333,45.798333,15.246667,38.498333,46.255000,2.561667,45.168333,2.933333,72.115000,9.568333,0.353333,78.791667,0.706667,18.681667,20.500000,2.726667,0.000000,62.178333,5.760000,28.088333,73.105000,12.900000,48.713333,0.616667,8.596667,24.993333,24.658333,31.021667,27.651667,27.271667,39.398333,15.776667,15.350000,74.833333,13.090000,29.563333,40.223333,17.126667,24.081667,3.891667,5.906667,8.693333,3.895000,1.531667,7.035000,5.151667,16.188333,69.786667,8.878333,0.000000,5.890000,23.945000,16.900000,19.155000,16.666667,16.605000,5.753333,11.181667,3268.500000
4,GGGGGGG9DSUDeNG,2017-10-20,5AGKS,17490,75,Male,0,0,0,1,0,0,RN,55,679044,0,0,0,0,0,25.014922,Overweight,0.0,3.0,0.774816,0.0,3.0,0.0,3.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,"Circulatory: I10., M62.81",-1,Isolated / Unclustered,-1,Isolated / Unclustered,-146,"Injury/Toxicity: S06.5X9D, S06.6X9D",-1,Isolated / Unclustered,-1,Isolated / Unclustered,"[-146, 0]","['Circulatory: I10., M62.81', 'Injury/Toxicity...",78250,TX,San Antonio,Texas,Bexar,1914732.0,95.29,94592.0,4.71,48029.0,17.100430,30.166559,10.333548,25.580242,16.550430,2.716290,57.600484,32.149113,40.689382,26.892419,7.250403,67.030591,7.775376,73.790323,12.738333,0.141909,82.810027,3.536747,7.949167,13.384597,2.844812,0.010753,72.448817,3.470511,7.419516,86.002016,13.045108,59.733844,0.696210,11.822661,36.228629,51.001774,13.347957,26.510323,27.626290,26.157177,9.183978,21.871290,154.072581,12.537661,31.599220,31.127957,24.466371,25.725833,7.061613,8.742715,15.345941,7.100591,3.711452,14.692366,5.239005,15.222742,62.818602,16.450484,12.744839,15.519355,20.763441,17.016720,14.259140,1.842903,17.247016,13.922527,9.413091,5228.276882
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
233268,GGGGGGXzUeSzeDG,2017-02-28,1CHMS,696200,65,Male,0,0,0,1,0,0,RN,57,747135.0,0,0,0,1,0,18.468756,Underweight,2.0,4.0,0.533915,5.0,7.0,5.0,7.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,-1,Isolated / Unclustered,-1,Isolated / Unclustered,0,"Circulatory: I10., M62.81",0,"Circulatory: I10., M62.81",0,"Circulatory: I10., M62.81",16,Musculoskeletal: M15.0,"[0, 16]","['Circulatory: I10., M62.81', 'Musculoskeletal...",78840,TX,Del Rio,Texas,Val Verde,42680.0,89.69,4906.0,10.31,48465.0,12.383571,25.620000,6.982857,21.909286,25.960714,0.390000,44.988571,24.814286,31.310714,36.732143,12.079286,47.477143,7.030000,54.884286,11.640000,0.016429,63.241429,2.994286,13.453571,26.620000,1.088571,0.000000,57.839286,3.133571,7.657143,74.266429,15.207143,48.401429,1.148571,12.099286,32.091429,42.495000,6.033571,30.043571,20.707143,30.723571,10.127143,18.692857,144.000000,10.379286,29.916429,22.145000,30.415000,28.607143,8.284286,10.098571,16.747857,6.849286,6.214286,13.560714,10.348571,13.810714,52.571429,16.126429,14.285714,0.000000,14.259286,16.330714,7.999286,0.000000,11.083571,14.567143,9.584286,3361.214286
233269,GGGGGGXzWGWNSDG,2017-08-19,2BFLS,10291,70,Male,0,0,1,0,0,0,RN,133,458134.0,0,1,1,1,1,23.329973,Normal weight,2.0,5.0,0.213643,10.0,13.0,12.0,15.0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,"Circulatory: I10., M62.81",0,"Circulatory: I10., M62.81",0,"Circulatory: I10., M62.81",3,Symptoms/Signs: R26.9,0,"Circulatory: I10., M62.81",1,Factors Influencing Health Status: Z99.81,"[0, 1, 3]","['Circulatory: I10., M62.81', 'Factors Influen...",78102,TX,Beeville,Texas,Bee,14230.0,45.83,16817.0,54.17,48025.0,6.917778,37.871111,6.153333,30.884444,18.175556,0.573333,50.940000,18.928889,42.297778,38.773333,3.375556,45.777778,2.960000,64.035556,11.254444,0.072222,69.218889,1.642222,14.920000,29.137778,0.543333,0.000000,64.862222,4.161111,16.940000,78.978889,14.335556,48.766667,0.675556,11.542222,25.627778,41.490000,22.880000,24.517778,26.934444,34.446667,14.145556,18.595556,100.222222,15.645556,30.817778,25.708889,27.828889,21.762222,8.594444,10.833333,13.883333,9.786667,2.121111,16.968889,4.797778,20.034444,56.525556,18.641111,0.000000,2.314444,13.298889,19.544444,10.981111,0.000000,20.194444,14.243333,10.246667,2749.666667
233270,GGGGGGXzWGzNXee,2017-05-21,1CHKT,661333,81,Male,0,0,0,1,0,0,RN,47,743142.0,0,0,0,1,0,20.980257,Normal weight,0.0,4.0,0.533915,0.0,4.0,0.0,4.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-1,Isolated / Unclustered,-1,Isolated / Unclustered,-1,Isolated / Unclustered,19,Factors Influencing Health Status: Z91.81,-1,Isolated / Unclustered,7,"Factors Influencing Health Status: Z96.641, M1...","[7, 19]","['Factors Influencing Health Status: Z91.81', ...",75051,TX,Grand Prairie,Texas,Dallas,21207.0,55.14,17255.0,44.86,1047.0,10.545294,31.229412,5.929412,35.907647,16.389412,6.047059,47.703529,12.586471,47.370588,40.040588,0.166471,41.618824,6.047059,62.783529,19.321176,0.419412,71.655294,1.708235,24.328824,26.637059,0.706471,0.000000,52.237059,5.984118,10.360588,65.979412,17.080588,39.018235,1.327059,20.106471,63.601765,38.752353,14.840588,46.407647,37.265294,35.581765,16.677647,26.692941,114.235294,13.866471,28.326471,19.230588,38.575882,53.601176,16.195294,8.889412,29.968824,10.930000,3.444706,23.831176,7.732353,17.348824,47.557647,27.362353,13.445294,0.000000,31.530000,8.717059,7.271176,0.000000,5.882353,13.491176,18.041176,2209.294118
233271,GGGGGGXzeeD99XU,2017-04-08,1CHMT,438968,67,Female,0,0,0,0,0,1,PT,12,747241.0,0,0,0,1,0,37.925849,Obese-Class2,0.0,2.0,0.901470,0.0,2.0,0.0,2.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,"Circulatory: I10., M62.81",27,"Factors Influencing Health Status: Z96.652, M1...",27,"Factors Influencing Health Status: Z96.652, M1...",10,Symptoms/Signs: R26.89,0,"Circulatory: I10., M62.81",0,"Circulatory: I10., M62.81","[0, 10, 27]","['Circulatory: I10., M62.81', 'Factors Influen...",75180,TX,Balch Springs,Texas,Dallas,21207.0,55.14,17255.0,44.86,1047.0,10.545294,31.229412,5.929412,35.907647,16.389412,6.047059,47.703529,12.586471,47.370588,40.040588,0.166471,41.618824,6.047059,62.783529,19.321176,0.419412,71.655294,1.708235,24.328824,26.637059,0.706471,0.000000,52.237059,5.984118,10.360588,65.979412,17.080588,39.018235,1.327059,20.106471,63.601765,38.752353,14.840588,46.407647,37.265294,35.581765,16.677647,26.692941,114.235294,13.866471,28.326471,19.230588,38.575882,53.601176,16.195294,8.889412,29.968824,10.930000,3.444706,23.831176,7.732353,17.348824,47.557647,27.362353,13.445294,0.000000,31.530000,8.717059,7.271176,0.000000,5.882353,13.491176,18.041176,2209.294118
233272,GGGGGGXzezWUUNG,2017-01-20,1CGKT,11748,59,Female,0,0,0,1,0,0,RN,69,677285.0,0,0,0,1,0,34.139898,Obese-Class1,0.0,1.0,0.958704,0.0,1.0,0.0,1.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,-67,"Skin/Subcutaneous: L02.31, L03.317",-67,"Skin/Subcutaneous: L02.31, L03.317",9,Endocrine/Metabolic: E11.65,0,"Circulatory: I10., M62.81",-1,Isolated / Unclustered,-1,Isolated / Unclustered,"[-67, 0, 9]","['Circulatory: I10., M62.81', 'Endocrine/Metab...",78504,TX,Mcallen,Texas,Hidalgo,0.0,0.00,4178.0,100.00,35023.0,13.355000,29.140000,6.570000,33.410000,17.525000,10.640000,49.065000,23.740000,32.215000,44.045000,5.585000,46.740000,7.720000,62.105000,14.940000,0.000000,73.440000,4.730000,15.970000,21.830000,0.455000,0.000000,60.260000,4.825000,15.065000,76.430000,19.920000,47.530000,0.235000,11.820000,28.040000,36.960000,63.040000,0.000000,26.225000,37.280000,12.480000,18.365000,50.000000,9.405000,38.615000,18.545000,33.430000,44.810000,13.385000,8.585000,21.760000,5.760000,6.025000,23.065000,8.160000,12.900000,57.155000,21.775000,27.780000,0.000000,100.000000,21.890000,11.590000,0.000000,3.450000,15.150000,9.850000,2060.500000

In [21]:
df_TX.columns.tolist()

['Beneficiary_ID',
 'Assessment_Effective_Date',
 'Submitted_HIPPS_Code',
 'Facility_Internal_ID',
 'Age',
 'Gender',
 'American_Indian_or_Alaska_Native',
 'Asian',
 'Black_or_African_American',
 'Hispanic_or_Latino',
 'Native_Hawiian_or_Pacific_Islander',
 'White',
 'ByDiscipline',
 'Days_Cared_For',
 'Agency_Medicare_Number',
 'has_diabetes',
 'has_heart_failure',
 'has_hypertension',
 'ever_deceased',
 'ever_readmitted',
 'BMI',
 'BMI_Category',
 'charlson_score',
 'charlson_ageadj',
 'charlson_survival_10yr',
 'elix_quan_score',
 'elix_quan_ageadj',
 'elix_swiss_score',
 'elix_swiss_ageadj',
 'aids',
 'alcohol',
 'ami',
 'blane',
 'canc',
 'carit',
 'cevd',
 'chf',
 'coag',
 'copd',
 'dane',
 'dementia',
 'depre',
 'diab',
 'diabc',
 'diabunc',
 'diabwc',
 'drug',
 'fed',
 'hp',
 'hypc',
 'hypothy',
 'hypunc',
 'ld',
 'lymph',
 'metacanc',
 'msld',
 'obes',
 'ond',
 'pcd',
 'psycho',
 'pud',
 'pvd',
 'rend',
 'rheumd',
 'valv',
 'wloss',
 'Primary_Diagnosis_ICD_10_C_M_Code_Cluster',
 'Primary_Diagnosis_ICD_10_C_M_Code_Cluster_Name',
 'Other_Diagnosis_Code_1_ICD_10_C_M_Cluster',
 'Other_Diagnosis_Code_1_ICD_10_C_M_Cluster_Name',
 'Other_Diagnosis_Code_2_ICD_10_C_M_Cluster',
 'Other_Diagnosis_Code_2_ICD_10_C_M_Cluster_Name',
 'Other_Diagnosis_Code_3_ICD_10_C_M_Cluster',
 'Other_Diagnosis_Code_3_ICD_10_C_M_Cluster_Name',
 'Other_Diagnosis_Code_4_ICD_10_C_M_Cluster',
 'Other_Diagnosis_Code_4_ICD_10_C_M_Cluster_Name',
 'Other_Diagnosis_Code_5_ICD_10_C_M_Cluster',
 'Other_Diagnosis_Code_5_ICD_10_C_M_Cluster_Name',
 'ICD_Clusters_In_Row',
 'ICD_Cluster_Names_In_Row',
 'zip',
 'state_id',
 'city',
 'state_name',
 'COUNTY_NAME',
 'POP_URB',
 'POPPCT_URB',
 'POP_RUR',
 'POPPCT_RUR',
 'COUNTYFIPS',
 'ACS_PCT_BACHELOR_DGR',
 'ACS_PCT_COLLEGE_ASSOCIATE_DGR',
 'ACS_PCT_GRADUATE_DGR',
 'ACS_PCT_HS_GRADUATE',
 'ACS_PCT_LT_HS',
 'ACS_PCT_NO_WORK_NO_SCHL_16_19',
 'ACS_PCT_POSTHS_ED',
 'ACS_PCT_VET_BACHELOR',
 'ACS_PCT_VET_COLLEGE',
 'ACS_PCT_VET_HS',
 'ACS_PCT_HH_LIMIT_ENGLISH',
 'ACS_PCT_HH_BROADBAND',
 'ACS_PCT_HH_BROADBAND_ONLY',
 'ACS_PCT_HH_CELLULAR',
 'ACS_PCT_HH_CELLULAR_ONLY',
 'ACS_PCT_HH_DIAL_INTERNET_ONLY',
 'ACS_PCT_HH_INTERNET',
 'ACS_PCT_HH_INTERNET_NO_SUBS',
 'ACS_PCT_HH_NO_COMP_DEV',
 'ACS_PCT_HH_NO_INTERNET',
 'ACS_PCT_HH_OTHER_COMP',
 'ACS_PCT_HH_OTHER_COMP_ONLY',
 'ACS_PCT_HH_PC',
 'ACS_PCT_HH_PC_ONLY',
 'ACS_PCT_HH_SAT_INTERNET',
 'ACS_PCT_HH_SMARTPHONE',
 'ACS_PCT_HH_SMARTPHONE_ONLY',
 'ACS_PCT_HH_TABLET',
 'ACS_PCT_HH_TABLET_ONLY',
 'ACS_PCT_CHILDREN_GRANDPARENT',
 'ACS_PCT_CHILD_1FAM',
 'ACS_PCT_GRANDP_NO_RESPS',
 'ACS_PCT_GRANDP_RESPS_NO_P',
 'ACS_PCT_GRANDP_RESPS_P',
 'ACS_PCT_HH_1PERS',
 'ACS_PCT_HH_ABOVE65',
 'ACS_PCT_HH_ALONE_ABOVE65',
 'ACS_PCT_HH_KID_1PRNT',
 'ACS_TOT_GRANDCHILDREN_GP',
 'ACS_PCT_HEALTH_INC_138_199',
 'ACS_PCT_HEALTH_INC_200_399',
 'ACS_PCT_HEALTH_INC_ABOVE400',
 'ACS_PCT_HEALTH_INC_BELOW137',
 'ACS_PCT_HH_1FAM_FOOD_STMP',
 'ACS_PCT_HH_FOOD_STMP_BLW_POV',
 'ACS_PCT_HH_NO_FD_STMP_BLW_POV',
 'ACS_PCT_HH_PUB_ASSIST',
 'ACS_PCT_INC50',
 'ACS_PCT_INC50_ABOVE65',
 'ACS_PCT_NONVET_POV_18_64',
 'ACS_PCT_PERSON_INC_100_124',
 'ACS_PCT_PERSON_INC_125_199',
 'ACS_PCT_PERSON_INC_ABOVE200',
 'ACS_PCT_PERSON_INC_BELOW99',
 'ACS_PCT_POV_AIAN',
 'ACS_PCT_POV_ASIAN',
 'ACS_PCT_POV_BLACK',
 'ACS_PCT_POV_HISPANIC',
 'ACS_PCT_POV_MULTI',
 'ACS_PCT_POV_NHPI',
 'ACS_PCT_POV_OTHER',
 'ACS_PCT_POV_WHITE',
 'ACS_PCT_VET_POV_18_64',
 'ACS_TOT_POP_POV']

In [22]:
for col in ["Facility_Internal_ID", "Agency_Medicare_Number"]:
    # Convert to numeric, turning non-numeric values into NaN
    df_TX[col] = pd.to_numeric(df_TX[col], errors="coerce")
    
    # If you are okay with dropping rows that have NaN in these columns:
    df_TX = df_TX.dropna(subset=[col])
    
    # Finally cast to integer type
    df_TX[col] = df_TX[col].astype("int64")

In [25]:
numeric_cols = ['Age', 'Days_Cared_For',
'charlson_score',
 'charlson_ageadj',
 'charlson_survival_10yr',
 'elix_quan_score',
 'elix_quan_ageadj',
 'elix_swiss_score',
 'elix_swiss_ageadj', 'POP_URB',
 'POPPCT_URB',
 'POP_RUR',
 'POPPCT_RUR','ACS_PCT_BACHELOR_DGR',
 'ACS_PCT_COLLEGE_ASSOCIATE_DGR',
 'ACS_PCT_GRADUATE_DGR',
 'ACS_PCT_HS_GRADUATE',
 'ACS_PCT_LT_HS',
 'ACS_PCT_NO_WORK_NO_SCHL_16_19',
 'ACS_PCT_POSTHS_ED',
 'ACS_PCT_VET_BACHELOR',
 'ACS_PCT_VET_COLLEGE',
 'ACS_PCT_VET_HS',
 'ACS_PCT_HH_LIMIT_ENGLISH',
 'ACS_PCT_HH_BROADBAND',
 'ACS_PCT_HH_BROADBAND_ONLY',
 'ACS_PCT_HH_CELLULAR',
 'ACS_PCT_HH_CELLULAR_ONLY',
 'ACS_PCT_HH_DIAL_INTERNET_ONLY',
 'ACS_PCT_HH_INTERNET',
 'ACS_PCT_HH_INTERNET_NO_SUBS',
 'ACS_PCT_HH_NO_COMP_DEV',
 'ACS_PCT_HH_NO_INTERNET',
 'ACS_PCT_HH_OTHER_COMP',
 'ACS_PCT_HH_OTHER_COMP_ONLY',
 'ACS_PCT_HH_PC',
 'ACS_PCT_HH_PC_ONLY',
 'ACS_PCT_HH_SAT_INTERNET',
 'ACS_PCT_HH_SMARTPHONE',
 'ACS_PCT_HH_SMARTPHONE_ONLY',
 'ACS_PCT_HH_TABLET',
 'ACS_PCT_HH_TABLET_ONLY',
 'ACS_PCT_CHILDREN_GRANDPARENT',
 'ACS_PCT_CHILD_1FAM',
 'ACS_PCT_GRANDP_NO_RESPS',
 'ACS_PCT_GRANDP_RESPS_NO_P',
 'ACS_PCT_GRANDP_RESPS_P',
 'ACS_PCT_HH_1PERS',
 'ACS_PCT_HH_ABOVE65',
 'ACS_PCT_HH_ALONE_ABOVE65',
 'ACS_PCT_HH_KID_1PRNT',
 'ACS_TOT_GRANDCHILDREN_GP',
 'ACS_PCT_HEALTH_INC_138_199',
 'ACS_PCT_HEALTH_INC_200_399',
 'ACS_PCT_HEALTH_INC_ABOVE400',
 'ACS_PCT_HEALTH_INC_BELOW137',
 'ACS_PCT_HH_1FAM_FOOD_STMP',
 'ACS_PCT_HH_FOOD_STMP_BLW_POV',
 'ACS_PCT_HH_NO_FD_STMP_BLW_POV',
 'ACS_PCT_HH_PUB_ASSIST',
 'ACS_PCT_INC50',
 'ACS_PCT_INC50_ABOVE65',
 'ACS_PCT_NONVET_POV_18_64',
 'ACS_PCT_PERSON_INC_100_124',
 'ACS_PCT_PERSON_INC_125_199',
 'ACS_PCT_PERSON_INC_ABOVE200',
 'ACS_PCT_PERSON_INC_BELOW99',
 'ACS_PCT_POV_AIAN',
 'ACS_PCT_POV_ASIAN',
 'ACS_PCT_POV_BLACK',
 'ACS_PCT_POV_HISPANIC',
 'ACS_PCT_POV_MULTI',
 'ACS_PCT_POV_NHPI',
 'ACS_PCT_POV_OTHER',
 'ACS_PCT_POV_WHITE',
 'ACS_PCT_VET_POV_18_64',
 'ACS_TOT_POP_POV'
]


flag_cols = ['American_Indian_or_Alaska_Native',
 'Asian',
 'Black_or_African_American',
 'Hispanic_or_Latino',
 'Native_Hawiian_or_Pacific_Islander',
 'White','has_diabetes',
 'has_heart_failure',
 'has_hypertension',
 'ever_deceased',
 'ever_readmitted','aids',
 'alcohol',
 'ami',
 'blane',
 'canc',
 'carit',
 'cevd',
 'chf',
 'coag',
 'copd',
 'dane',
 'dementia',
 'depre',
 'diab',
 'diabc',
 'diabunc',
 'diabwc',
 'drug',
 'fed',
 'hp',
 'hypc',
 'hypothy',
 'hypunc',
 'ld',
 'lymph',
 'metacanc',
 'msld',
 'obes',
 'ond',
 'pcd',
 'psycho',
 'pud',
 'pvd',
 'rend',
 'rheumd',
 'valv',
 'wloss']

In [27]:
for col in flag_cols:
    assert set(df_TX[col].dropna().unique()).issubset({0, 1}), f"{col} not binary"

# Coerce numeric columns to numeric type
for col in numeric_cols:
    df_TX[col] = pd.to_numeric(df_TX[col], errors="coerce")

# Optionally drop rows with missing numeric data (if required)
df_TX = df_TX.dropna(subset=numeric_cols)

# Round numeric columns to 2 decimal places
df_TX[numeric_cols] = df_TX[numeric_cols].round(2)

In [28]:
df_TX

,Beneficiary_ID,Assessment_Effective_Date,Submitted_HIPPS_Code,Facility_Internal_ID,Age,Gender,American_Indian_or_Alaska_Native,Asian,Black_or_African_American,Hispanic_or_Latino,Native_Hawiian_or_Pacific_Islander,White,ByDiscipline,Days_Cared_For,Agency_Medicare_Number,has_diabetes,has_heart_failure,has_hypertension,ever_deceased,ever_readmitted,BMI,BMI_Category,charlson_score,charlson_ageadj,charlson_survival_10yr,elix_quan_score,elix_quan_ageadj,elix_swiss_score,elix_swiss_ageadj,aids,alcohol,ami,blane,canc,carit,cevd,chf,coag,copd,dane,dementia,depre,diab,diabc,diabunc,diabwc,drug,fed,hp,hypc,hypothy,hypunc,ld,lymph,metacanc,msld,obes,ond,pcd,psycho,pud,pvd,rend,rheumd,valv,wloss,Primary_Diagnosis_ICD_10_C_M_Code_Cluster,Primary_Diagnosis_ICD_10_C_M_Code_Cluster_Name,Other_Diagnosis_Code_1_ICD_10_C_M_Cluster,Other_Diagnosis_Code_1_ICD_10_C_M_Cluster_Name,Other_Diagnosis_Code_2_ICD_10_C_M_Cluster,Other_Diagnosis_Code_2_ICD_10_C_M_Cluster_Name,Other_Diagnosis_Code_3_ICD_10_C_M_Cluster,Other_Diagnosis_Code_3_ICD_10_C_M_Cluster_Name,Other_Diagnosis_Code_4_ICD_10_C_M_Cluster,Other_Diagnosis_Code_4_ICD_10_C_M_Cluster_Name,Other_Diagnosis_Code_5_ICD_10_C_M_Cluster,Other_Diagnosis_Code_5_ICD_10_C_M_Cluster_Name,ICD_Clusters_In_Row,ICD_Cluster_Names_In_Row,zip,state_id,city,state_name,COUNTY_NAME,POP_URB,POPPCT_URB,POP_RUR,POPPCT_RUR,COUNTYFIPS,ACS_PCT_BACHELOR_DGR,ACS_PCT_COLLEGE_ASSOCIATE_DGR,ACS_PCT_GRADUATE_DGR,ACS_PCT_HS_GRADUATE,ACS_PCT_LT_HS,ACS_PCT_NO_WORK_NO_SCHL_16_19,ACS_PCT_POSTHS_ED,ACS_PCT_VET_BACHELOR,ACS_PCT_VET_COLLEGE,ACS_PCT_VET_HS,ACS_PCT_HH_LIMIT_ENGLISH,ACS_PCT_HH_BROADBAND,ACS_PCT_HH_BROADBAND_ONLY,ACS_PCT_HH_CELLULAR,ACS_PCT_HH_CELLULAR_ONLY,ACS_PCT_HH_DIAL_INTERNET_ONLY,ACS_PCT_HH_INTERNET,ACS_PCT_HH_INTERNET_NO_SUBS,ACS_PCT_HH_NO_COMP_DEV,ACS_PCT_HH_NO_INTERNET,ACS_PCT_HH_OTHER_COMP,ACS_PCT_HH_OTHER_COMP_ONLY,ACS_PCT_HH_PC,ACS_PCT_HH_PC_ONLY,ACS_PCT_HH_SAT_INTERNET,ACS_PCT_HH_SMARTPHONE,ACS_PCT_HH_SMARTPHONE_ONLY,ACS_PCT_HH_TABLET,ACS_PCT_HH_TABLET_ONLY,ACS_PCT_CHILDREN_GRANDPARENT,ACS_PCT_CHILD_1FAM,ACS_PCT_GRANDP_NO_RESPS,ACS_PCT_GRANDP_RESPS_NO_P,ACS_PCT_GRANDP_RESPS_P,ACS_PCT_HH_1PERS,ACS_PCT_HH_ABOVE65,ACS_PCT_HH_ALONE_ABOVE65,ACS_PCT_HH_KID_1PRNT,ACS_TOT_GRANDCHILDREN_GP,ACS_PCT_HEALTH_INC_138_199,ACS_PCT_HEALTH_INC_200_399,ACS_PCT_HEALTH_INC_ABOVE400,ACS_PCT_HEALTH_INC_BELOW137,ACS_PCT_HH_1FAM_FOOD_STMP,ACS_PCT_HH_FOOD_STMP_BLW_POV,ACS_PCT_HH_NO_FD_STMP_BLW_POV,ACS_PCT_HH_PUB_ASSIST,ACS_PCT_INC50,ACS_PCT_INC50_ABOVE65,ACS_PCT_NONVET_POV_18_64,ACS_PCT_PERSON_INC_100_124,ACS_PCT_PERSON_INC_125_199,ACS_PCT_PERSON_INC_ABOVE200,ACS_PCT_PERSON_INC_BELOW99,ACS_PCT_POV_AIAN,ACS_PCT_POV_ASIAN,ACS_PCT_POV_BLACK,ACS_PCT_POV_HISPANIC,ACS_PCT_POV_MULTI,ACS_PCT_POV_NHPI,ACS_PCT_POV_OTHER,ACS_PCT_POV_WHITE,ACS_PCT_VET_POV_18_64,ACS_TOT_POP_POV
0,GGGGGGG99DzGeze,2017-03-17,1AGKU,334582,46,Female,0,0,1,0,0,0,RN,25,677994,0,0,0,1,1,29.898299,Overweight,4.0,4.0,0.53,9.0,9.0,18.0,18.0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,-1,Isolated / Unclustered,-141,"Symptoms/Signs: R10.11, R10.31",2,Genitourinary: N18.5,-1,Isolated / Unclustered,26,"Factors Influencing Health Status: Z45.2, Z79.2",0,"Circulatory: I10., M62.81","[-141, 0, 2, 26]","['Circulatory: I10., M62.81', 'Factors Influen...",77037,TX,Houston,Texas,Harris,974.0,2.81,33694.0,97.19,13145.0,18.74,36.04,13.01,25.43,6.78,1.93,67.79,34.93,43.62,21.45,0.14,67.00,7.26,75.97,12.11,0.29,85.78,1.48,5.61,12.74,2.68,0.00,81.01,4.25,9.70,86.35,9.49,68.82,0.48,9.28,17.44,40.38,18.25,41.37,18.48,33.23,8.75,11.34,91.57,9.89,32.28,47.67,10.15,25.71,2.96,2.59,7.87,3.26,1.66,5.77,2.60,11.64,79.96,5.80,0.00,2.84,5.63,4.00,6.30,0.00,0.00,5.32,0.82,4868.57
1,GGGGGGG9DDWNGGz,2017-02-28,2CGKU,487590,74,Female,0,0,0,0,0,1,RN,54,679724,0,0,0,1,0,33.197222,Obese-Class1,1.0,4.0,0.53,3.0,6.0,0.0,3.0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,"Circulatory: I10., M62.81",-1,Isolated / Unclustered,-1,Isolated / Unclustered,0,"Circulatory: I10., M62.81",0,"Circulatory: I10., M62.81",15,"Endocrine/Metabolic: E78.5, E03.9","[0, 15]","['Circulatory: I10., M62.81', 'Endocrine/Metab...",75044,TX,Garland,Texas,Dallas,21207.0,55.14,17255.0,44.86,1047.0,10.55,31.23,5.93,35.91,16.39,6.05,47.70,12.59,47.37,40.04,0.17,41.62,6.05,62.78,19.32,0.42,71.66,1.71,24.33,26.64,0.71,0.00,52.24,5.98,10.36,65.98,17.08,39.02,1.33,20.11,63.60,38.75,14.84,46.41,37.27,35.58,16.68,26.69,114.24,13.87,28.33,19.23,38.58,53.60,16.20,8.89,29.97,10.93,3.44,23.83,7.73,17.35,47.56,27.36,13.45,0.00,31.53,8.72,7.27,0.00,5.88,13.49,18.04,2209.29
2,GGGGGGG9DDWWeeX,2017-10-22,1CHKS,63847,75,Male,0,0,0,0,0,1,RN,37,679236,0,0,0,1,0,27.194009,Overweight,1.0,4.0,0.53,0.0,3.0,0.0,3.0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,4,"Factors Influencing Health Status: Z48.812, I21.4",-1,Isolated / Unclustered,-1,Isolated / Unclustered,0,"Circulatory: I10., M62.81",0,"Circulatory: I10., M62.81",21,Mental/Behavioral: F03.90,"[0, 4, 21]","['Circulatory: I10., M62.81', 'Factors Influen...",75070,TX,Mckinney,Texas,Collin,999005.0,93.85,65460.0,6.15,48085.0,33.54,26.08,19.29,14.45,6.19,0.71,78.91,47.77,35.08,15.79,4.92,83.97,8.10,84.43,6.47,0.07,93.58,1.30,1.71,4.67,4.17,0.04,90.94,2.37,7.72,93.95,4.40,74.76,0.33,3.90,20.27,34.62,12.42,20.24,21.79,21.08,6.32,12.98,45.88,6.62,23.73,58.46,10.74,7.27,0.90,5.73,3.43,3.96,4.07,6.55,2.37,7.98,82.18,7.00,4.33,8.70,8.22,8.85,7.92,1.07,7.40,5.32,4.17,4546.33
3,GGGGGGG9DGXzUSG,2017-09-13,1BHKT,10206,75,Male,0,0,0,0,0,1,RN,57,677247,0,0,0,0,0,22.594123,Normal weight,0.0,3.0,0.77,0.0,3.0,0.0,3.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-1,Isolated / Unclustered,26,"Factors Influencing Health Status: Z45.2, Z79.2",0,"Circulatory: I10., M62.81",-108,"Musculoskeletal: M21.371, M21.372",-108,"Musculoskeletal: M21.371, M21.372",-1,Isolated / Unclustered,"[-108, 0, 26]","['Circulatory: I10., M62.81', 'Factors Influen...",77975,TX,Moulton,Texas,Lavaca,3582.0,17.61,16755.0,82.39,48285.0,12.98,28.17,4.65,40.46,13.74,4.69,45.80,15.25,38.50,46.26,2.56,45.17,2.93,72.11,9.57,0.35,78.79,0.71,18.68,20.50,2.73,0.00,62.18,5.76,28.09,73.10,12.90,48.71,0.62,8.60,24.99,24.66,31.02,27.65,27.27,39.40,15.78,15.35,74.83,13.09,29.56,40.22,17.13,24.08,3.89,5.91,8.69,3.90,1.53,7.04,5.15,16.19,69.79,8.88,0.00,5.89,23.94,16.90,19.16,16.67,16.60,5.75,11.18,3268.50
4,GGGGGGG9DSUDeNG,2017-10-20,5AGKS,17490,75,Male,0,0,0,1,0,0,RN,55,679044,0,0,0,0,0,25.014922,Overweight,0.0,3.0,0.77,0.0,3.0,0.0,3.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,"Circulatory: I10., M62.81",-1,Isolated / Unclustered,-1,Isolated / Unclustered,-146,"Injury/Toxicity: S06.5X9D, S06.6X9D",-1,Isolated / Unclustered,-1,Isolated / Unclustered,"[-146, 0]","['Circulatory: I10., M62.81', 'Injury/Toxicity...",78250,TX,San Antonio,Texas,Bexar,1914732.0,95.29,94592.0,4.71,48029.0,17.10,30.17,10.33,25.58,16.55,2.72,57.60,32.15,40.69,26.89,7.25,67.03,7.78,73.79,12.74,0.14,82.81,3.54,7.95,13.38,2.84,0.01,72.45,3.47,7.42,86.00,13.05,59.73,0.70,11.82,36.23,51.00,13.35,26.51,27.63,26.16,9.18,21.87,154.07,12.54,31.60,31.13,24.47,25.73,7.06,8.74,15.35,7.10,3.71,14.69,5.24,15.22,62.82,16.45,12.74,15.52,20.76,17.02,14.26,1.84,17.25,13.92,9.41,5228.28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
233268,GGGGGGXzUeSzeDG,2017-02-28,1CHMS,696200,65,Male,0,0,0,1,0,0,RN,57,747135,0,0,0,1,0,18.468756,Underweight,2.0,4.0,0.53,5.0,7.0,5.0,7.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,-1,Isolated / Unclustered,-1,Isolated / Unclustered,0,"Circulatory: I10., M62.81",0,"Circulatory: I10., M62.81",0,"Circulatory: I10., M62.81",16,Musculoskeletal: M15.0,"[0, 16]","['Circulatory: I10., M62.81', 'Musculoskeletal...",78840,TX,Del Rio,Texas,Val Verde,42680.0,89.69,4906.0,10.31,48465.0,12.38,25.62,6.98,21.91,25.96,0.39,44.99,24.81,31.31,36.73,12.08,47.48,7.03,54.88,11.64,0.02,63.24,2.99,13.45,26.62,1.09,0.00,57.84,3.13,7.66,74.27,15.21,48.40,1.15,12.10,32.09,42.50,6.03,30.04,20.71,30.72,10.13,18.69,144.00,10.38,29.92,22.14,30.42,28.61,8.28,10.10,16.75,6.85,6.21,13.56,10.35,13.81,52.57,16.13,14.29,0.00,14.26,16.33,8.00,0.00,11.08,14.57,9.58,3361.21
233269,GGGGGGXzWGWNSDG,2017-08-19,2BFLS,10291,70,Male,0,0,1,0,0,0,RN,133,458134,0,1,1,1,1,23.329973,Normal weight,2.0,5.0,0.21,10.0,13.0,12.0,15.0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,"Circulatory: I10., M62.81",0,"Circulatory: I10., M62.81",0,"Circulatory: I10., M62.81",3,Symptoms/Signs: R26.9,0,"Circulatory: I10., M62.81",1,Factors Influencing Health Status: Z99.81,"[0, 1, 3]","['Circulatory: I10., M62.81', 'Factors Influen...",78102,TX,Beeville,Texas,Bee,14230.0,45.83,16817.0,54.17,48025.0,6.92,37.87,6.15,30.88,18.18,0.57,50.94,18.93,42.30,38.77,3.38,45.78,2.96,64.04,11.25,0.07,69.22,1.64,14.92,29.14,0.54,0.00,64.86,4.16,16.94,78.98,14.34,48.77,0.68,11.54,25.63,41.49,22.88,24.52,26.93,34.45,14.15,18.60,100.22,15.65,30.82,25.71,27.83,21.76,8.59,10.83,13.88,9.79,2.12,16.97,4.80,20.03,56.53,18.64,0.00,2.31,13.30,19.54,10.98,0.00,20.19,14.24,10.25,2749.67
233270,GGGGGGXzWGzNXee,2017-05-21,1CHKT,661333,81,Male,0,0,0,1,0,0,RN,47,743142,0,0,0,1,0,20.980257,Normal weight,0.0,4.0,0.53,0.0,4.0,0.0,4.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-1,Isolated / Unclustered,-1,Isolated / Unclustered,-1,Isolated / Unclustered,19,Factors Influencing Health Status: Z91.81,-1,Isolated / Unclustered,7,"Factors Influencing Health Status: Z96.641, M1...","[7, 19]","['Factors Influencing Health Status: Z91.81', ...",75051,TX,Grand Prairie,Texas,Dallas,21207.0,55.14,17255.0,44.86,1047.0,10.55,31.23,5.93,35.91,16.39,6.05,47.70,12.59,47.37,40.04,0.17,41.62,6.05,62.78,19.32,0.42,71.66,1.71,24.33,26.64,0.71,0.00,52.24,5.98,10.36,65.98,17.08,39.02,1.33,20.11,63.60,38.75,14.84,46.41,37.27,35.58,16.68,26.69,114.24,13.87,28.33,19.23,38.58,53.60,16.20,8.89,29.97,10.93,3.44,23.83,7.73,17.35,47.56,27.36,13.45,0.00,31.53,8.72,7.27,0.00,5.88,13.49,18.04,2209.29
233271,GGGGGGXzeeD99XU,2017-04-08,1CHMT,438968,67,Female,0,0,0,0,0,1,PT,12,747241,0,0,0,1,0,37.925849,Obese-Class2,0.0,2.0,0.90,0.0,2.0,0.0,2.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,"Circulatory: I10., M62.81",27,"Factors Influencing Health Status: Z96.652, M1...",27,"Factors Influencing Health Status: Z96.652, M1...",10,Symptoms/Signs: R26.89,0,"Circulatory: I10., M62.81",0,"Circulatory: I10., M62.81","[0, 10, 27]","['Circulatory: I10., M62.81', 'Factors Influen...",75180,TX,Balch Springs,Texas,Dallas,21207.0,55.14,17255.0,44.86,1047.0,10.55,31.23,5.93,35.91,16.39,6.05,47.70,12.59,47.37,40.04,0.17,41.62,6.05,62.78,19.32,0.42,71.66,1.71,24.33,26.64,0.71,0.00,52.24,5.98,10.36,65.98,17.08,39.02,1.33,20.11,63.60,38.75,14.84,46.41,37.27,35.58,16.68,26.69,114.24,13.87,28.33,19.23,38.58,53.60,16.20,8.89,29.97,10.93,3.44,23.83,7.73,17.35,47.56,27.36,13.45,0.00,31.53,8.72,7.27,0.00,5.88,13.49,18.04,2209.29
233272,GGGGGGXzezWUUNG,2017-01-20,1CGKT,11748,59,Female,0,0,0,1,0,0,RN,69,677285,0,0,0,1,0,34.139898,Obese-Class1,0.0,1.0,0.96,0.0,1.0,0.0,1.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,-67,"Skin/Subcutaneous: L02.31, L03.317",-67,"Skin/Subcutaneous: L02.31, L03.317",9,Endocrine/Metabolic: E11.65,0,"Circulatory: I10., M62.81",-1,Isolated / Unclustered,-1,Isolated / Unclustered,"[-67, 0, 9]","['Circulatory: I10., M62.81', 'Endocrine/Metab...",78504,TX,Mcallen,Texas,Hidalgo,0.0,0.00,4178.0,100.00,35023.0,13.36,29.14,6.57,33.41,17.52,10.64,49.06,23.74,32.22,44.04,5.58,46.74,7.72,62.10,14.94,0.00,73.44,4.73,15.97,21.83,0.46,0.00,60.26,4.82,15.06,76.43,19.92,47.53,0.24,11.82,28.04,36.96,63.04,0.00,26.22,37.28,12.48,18.36,50.00,9.40,38.62,18.55,33.43,44.81,13.38,8.59,21.76,5.76,6.02,23.06,8.16,12.90,57.16,21.78,27.78,0.00,100.00,21.89,11.59,0.00,3.45,15.15,9.85,2060.50

In [29]:
drop_cols = ['zip', 'city',
 'state_name','COUNTYFIPS','BMI',
 'Primary_Diagnosis_ICD_10_C_M_Code_Cluster_Name',
 'Other_Diagnosis_Code_1_ICD_10_C_M_Cluster_Name',
 'Other_Diagnosis_Code_2_ICD_10_C_M_Cluster_Name',
 'Other_Diagnosis_Code_3_ICD_10_C_M_Cluster_Name',
 'Other_Diagnosis_Code_4_ICD_10_C_M_Cluster_Name',
 'Other_Diagnosis_Code_5_ICD_10_C_M_Cluster_Name',
 'ICD_Clusters_In_Row','Assessment_Effective_Date',
 'ICD_Cluster_Names_In_Row']
df_TX = df_TX.drop(columns=drop_cols, errors="ignore")
df_TX

,Beneficiary_ID,Submitted_HIPPS_Code,Facility_Internal_ID,Age,Gender,American_Indian_or_Alaska_Native,Asian,Black_or_African_American,Hispanic_or_Latino,Native_Hawiian_or_Pacific_Islander,White,ByDiscipline,Days_Cared_For,Agency_Medicare_Number,has_diabetes,has_heart_failure,has_hypertension,ever_deceased,ever_readmitted,BMI_Category,charlson_score,charlson_ageadj,charlson_survival_10yr,elix_quan_score,elix_quan_ageadj,elix_swiss_score,elix_swiss_ageadj,aids,alcohol,ami,blane,canc,carit,cevd,chf,coag,copd,dane,dementia,depre,diab,diabc,diabunc,diabwc,drug,fed,hp,hypc,hypothy,hypunc,ld,lymph,metacanc,msld,obes,ond,pcd,psycho,pud,pvd,rend,rheumd,valv,wloss,Primary_Diagnosis_ICD_10_C_M_Code_Cluster,Other_Diagnosis_Code_1_ICD_10_C_M_Cluster,Other_Diagnosis_Code_2_ICD_10_C_M_Cluster,Other_Diagnosis_Code_3_ICD_10_C_M_Cluster,Other_Diagnosis_Code_4_ICD_10_C_M_Cluster,Other_Diagnosis_Code_5_ICD_10_C_M_Cluster,state_id,COUNTY_NAME,POP_URB,POPPCT_URB,POP_RUR,POPPCT_RUR,ACS_PCT_BACHELOR_DGR,ACS_PCT_COLLEGE_ASSOCIATE_DGR,ACS_PCT_GRADUATE_DGR,ACS_PCT_HS_GRADUATE,ACS_PCT_LT_HS,ACS_PCT_NO_WORK_NO_SCHL_16_19,ACS_PCT_POSTHS_ED,ACS_PCT_VET_BACHELOR,ACS_PCT_VET_COLLEGE,ACS_PCT_VET_HS,ACS_PCT_HH_LIMIT_ENGLISH,ACS_PCT_HH_BROADBAND,ACS_PCT_HH_BROADBAND_ONLY,ACS_PCT_HH_CELLULAR,ACS_PCT_HH_CELLULAR_ONLY,ACS_PCT_HH_DIAL_INTERNET_ONLY,ACS_PCT_HH_INTERNET,ACS_PCT_HH_INTERNET_NO_SUBS,ACS_PCT_HH_NO_COMP_DEV,ACS_PCT_HH_NO_INTERNET,ACS_PCT_HH_OTHER_COMP,ACS_PCT_HH_OTHER_COMP_ONLY,ACS_PCT_HH_PC,ACS_PCT_HH_PC_ONLY,ACS_PCT_HH_SAT_INTERNET,ACS_PCT_HH_SMARTPHONE,ACS_PCT_HH_SMARTPHONE_ONLY,ACS_PCT_HH_TABLET,ACS_PCT_HH_TABLET_ONLY,ACS_PCT_CHILDREN_GRANDPARENT,ACS_PCT_CHILD_1FAM,ACS_PCT_GRANDP_NO_RESPS,ACS_PCT_GRANDP_RESPS_NO_P,ACS_PCT_GRANDP_RESPS_P,ACS_PCT_HH_1PERS,ACS_PCT_HH_ABOVE65,ACS_PCT_HH_ALONE_ABOVE65,ACS_PCT_HH_KID_1PRNT,ACS_TOT_GRANDCHILDREN_GP,ACS_PCT_HEALTH_INC_138_199,ACS_PCT_HEALTH_INC_200_399,ACS_PCT_HEALTH_INC_ABOVE400,ACS_PCT_HEALTH_INC_BELOW137,ACS_PCT_HH_1FAM_FOOD_STMP,ACS_PCT_HH_FOOD_STMP_BLW_POV,ACS_PCT_HH_NO_FD_STMP_BLW_POV,ACS_PCT_HH_PUB_ASSIST,ACS_PCT_INC50,ACS_PCT_INC50_ABOVE65,ACS_PCT_NONVET_POV_18_64,ACS_PCT_PERSON_INC_100_124,ACS_PCT_PERSON_INC_125_199,ACS_PCT_PERSON_INC_ABOVE200,ACS_PCT_PERSON_INC_BELOW99,ACS_PCT_POV_AIAN,ACS_PCT_POV_ASIAN,ACS_PCT_POV_BLACK,ACS_PCT_POV_HISPANIC,ACS_PCT_POV_MULTI,ACS_PCT_POV_NHPI,ACS_PCT_POV_OTHER,ACS_PCT_POV_WHITE,ACS_PCT_VET_POV_18_64,ACS_TOT_POP_POV
0,GGGGGGG99DzGeze,1AGKU,334582,46,Female,0,0,1,0,0,0,RN,25,677994,0,0,0,1,1,Overweight,4.0,4.0,0.53,9.0,9.0,18.0,18.0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,-1,-141,2,-1,26,0,TX,Harris,974.0,2.81,33694.0,97.19,18.74,36.04,13.01,25.43,6.78,1.93,67.79,34.93,43.62,21.45,0.14,67.00,7.26,75.97,12.11,0.29,85.78,1.48,5.61,12.74,2.68,0.00,81.01,4.25,9.70,86.35,9.49,68.82,0.48,9.28,17.44,40.38,18.25,41.37,18.48,33.23,8.75,11.34,91.57,9.89,32.28,47.67,10.15,25.71,2.96,2.59,7.87,3.26,1.66,5.77,2.60,11.64,79.96,5.80,0.00,2.84,5.63,4.00,6.30,0.00,0.00,5.32,0.82,4868.57
1,GGGGGGG9DDWNGGz,2CGKU,487590,74,Female,0,0,0,0,0,1,RN,54,679724,0,0,0,1,0,Obese-Class1,1.0,4.0,0.53,3.0,6.0,0.0,3.0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-1,-1,0,0,15,TX,Dallas,21207.0,55.14,17255.0,44.86,10.55,31.23,5.93,35.91,16.39,6.05,47.70,12.59,47.37,40.04,0.17,41.62,6.05,62.78,19.32,0.42,71.66,1.71,24.33,26.64,0.71,0.00,52.24,5.98,10.36,65.98,17.08,39.02,1.33,20.11,63.60,38.75,14.84,46.41,37.27,35.58,16.68,26.69,114.24,13.87,28.33,19.23,38.58,53.60,16.20,8.89,29.97,10.93,3.44,23.83,7.73,17.35,47.56,27.36,13.45,0.00,31.53,8.72,7.27,0.00,5.88,13.49,18.04,2209.29
2,GGGGGGG9DDWWeeX,1CHKS,63847,75,Male,0,0,0,0,0,1,RN,37,679236,0,0,0,1,0,Overweight,1.0,4.0,0.53,0.0,3.0,0.0,3.0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,4,-1,-1,0,0,21,TX,Collin,999005.0,93.85,65460.0,6.15,33.54,26.08,19.29,14.45,6.19,0.71,78.91,47.77,35.08,15.79,4.92,83.97,8.10,84.43,6.47,0.07,93.58,1.30,1.71,4.67,4.17,0.04,90.94,2.37,7.72,93.95,4.40,74.76,0.33,3.90,20.27,34.62,12.42,20.24,21.79,21.08,6.32,12.98,45.88,6.62,23.73,58.46,10.74,7.27,0.90,5.73,3.43,3.96,4.07,6.55,2.37,7.98,82.18,7.00,4.33,8.70,8.22,8.85,7.92,1.07,7.40,5.32,4.17,4546.33
3,GGGGGGG9DGXzUSG,1BHKT,10206,75,Male,0,0,0,0,0,1,RN,57,677247,0,0,0,0,0,Normal weight,0.0,3.0,0.77,0.0,3.0,0.0,3.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-1,26,0,-108,-108,-1,TX,Lavaca,3582.0,17.61,16755.0,82.39,12.98,28.17,4.65,40.46,13.74,4.69,45.80,15.25,38.50,46.26,2.56,45.17,2.93,72.11,9.57,0.35,78.79,0.71,18.68,20.50,2.73,0.00,62.18,5.76,28.09,73.10,12.90,48.71,0.62,8.60,24.99,24.66,31.02,27.65,27.27,39.40,15.78,15.35,74.83,13.09,29.56,40.22,17.13,24.08,3.89,5.91,8.69,3.90,1.53,7.04,5.15,16.19,69.79,8.88,0.00,5.89,23.94,16.90,19.16,16.67,16.60,5.75,11.18,3268.50
4,GGGGGGG9DSUDeNG,5AGKS,17490,75,Male,0,0,0,1,0,0,RN,55,679044,0,0,0,0,0,Overweight,0.0,3.0,0.77,0.0,3.0,0.0,3.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-1,-1,-146,-1,-1,TX,Bexar,1914732.0,95.29,94592.0,4.71,17.10,30.17,10.33,25.58,16.55,2.72,57.60,32.15,40.69,26.89,7.25,67.03,7.78,73.79,12.74,0.14,82.81,3.54,7.95,13.38,2.84,0.01,72.45,3.47,7.42,86.00,13.05,59.73,0.70,11.82,36.23,51.00,13.35,26.51,27.63,26.16,9.18,21.87,154.07,12.54,31.60,31.13,24.47,25.73,7.06,8.74,15.35,7.10,3.71,14.69,5.24,15.22,62.82,16.45,12.74,15.52,20.76,17.02,14.26,1.84,17.25,13.92,9.41,5228.28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
233268,GGGGGGXzUeSzeDG,1CHMS,696200,65,Male,0,0,0,1,0,0,RN,57,747135,0,0,0,1,0,Underweight,2.0,4.0,0.53,5.0,7.0,5.0,7.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,-1,-1,0,0,0,16,TX,Val Verde,42680.0,89.69,4906.0,10.31,12.38,25.62,6.98,21.91,25.96,0.39,44.99,24.81,31.31,36.73,12.08,47.48,7.03,54.88,11.64,0.02,63.24,2.99,13.45,26.62,1.09,0.00,57.84,3.13,7.66,74.27,15.21,48.40,1.15,12.10,32.09,42.50,6.03,30.04,20.71,30.72,10.13,18.69,144.00,10.38,29.92,22.14,30.42,28.61,8.28,10.10,16.75,6.85,6.21,13.56,10.35,13.81,52.57,16.13,14.29,0.00,14.26,16.33,8.00,0.00,11.08,14.57,9.58,3361.21
233269,GGGGGGXzWGWNSDG,2BFLS,10291,70,Male,0,0,1,0,0,0,RN,133,458134,0,1,1,1,1,Normal weight,2.0,5.0,0.21,10.0,13.0,12.0,15.0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,0,1,TX,Bee,14230.0,45.83,16817.0,54.17,6.92,37.87,6.15,30.88,18.18,0.57,50.94,18.93,42.30,38.77,3.38,45.78,2.96,64.04,11.25,0.07,69.22,1.64,14.92,29.14,0.54,0.00,64.86,4.16,16.94,78.98,14.34,48.77,0.68,11.54,25.63,41.49,22.88,24.52,26.93,34.45,14.15,18.60,100.22,15.65,30.82,25.71,27.83,21.76,8.59,10.83,13.88,9.79,2.12,16.97,4.80,20.03,56.53,18.64,0.00,2.31,13.30,19.54,10.98,0.00,20.19,14.24,10.25,2749.67
233270,GGGGGGXzWGzNXee,1CHKT,661333,81,Male,0,0,0,1,0,0,RN,47,743142,0,0,0,1,0,Normal weight,0.0,4.0,0.53,0.0,4.0,0.0,4.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-1,-1,-1,19,-1,7,TX,Dallas,21207.0,55.14,17255.0,44.86,10.55,31.23,5.93,35.91,16.39,6.05,47.70,12.59,47.37,40.04,0.17,41.62,6.05,62.78,19.32,0.42,71.66,1.71,24.33,26.64,0.71,0.00,52.24,5.98,10.36,65.98,17.08,39.02,1.33,20.11,63.60,38.75,14.84,46.41,37.27,35.58,16.68,26.69,114.24,13.87,28.33,19.23,38.58,53.60,16.20,8.89,29.97,10.93,3.44,23.83,7.73,17.35,47.56,27.36,13.45,0.00,31.53,8.72,7.27,0.00,5.88,13.49,18.04,2209.29
233271,GGGGGGXzeeD99XU,1CHMT,438968,67,Female,0,0,0,0,0,1,PT,12,747241,0,0,0,1,0,Obese-Class2,0.0,2.0,0.90,0.0,2.0,0.0,2.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,27,27,10,0,0,TX,Dallas,21207.0,55.14,17255.0,44.86,10.55,31.23,5.93,35.91,16.39,6.05,47.70,12.59,47.37,40.04,0.17,41.62,6.05,62.78,19.32,0.42,71.66,1.71,24.33,26.64,0.71,0.00,52.24,5.98,10.36,65.98,17.08,39.02,1.33,20.11,63.60,38.75,14.84,46.41,37.27,35.58,16.68,26.69,114.24,13.87,28.33,19.23,38.58,53.60,16.20,8.89,29.97,10.93,3.44,23.83,7.73,17.35,47.56,27.36,13.45,0.00,31.53,8.72,7.27,0.00,5.88,13.49,18.04,2209.29
233272,GGGGGGXzezWUUNG,1CGKT,11748,59,Female,0,0,0,1,0,0,RN,69,677285,0,0,0,1,0,Obese-Class1,0.0,1.0,0.96,0.0,1.0,0.0,1.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,-67,-67,9,0,-1,-1,TX,Hidalgo,0.0,0.00,4178.0,100.00,13.36,29.14,6.57,33.41,17.52,10.64,49.06,23.74,32.22,44.04,5.58,46.74,7.72,62.10,14.94,0.00,73.44,4.73,15.97,21.83,0.46,0.00,60.26,4.82,15.06,76.43,19.92,47.53,0.24,11.82,28.04,36.96,63.04,0.00,26.22,37.28,12.48,18.36,50.00,9.40,38.62,18.55,33.43,44.81,13.38,8.59,21.76,5.76,6.02,23.06,8.16,12.90,57.16,21.78,27.78,0.00,100.00,21.89,11.59,0.00,3.45,15.15,9.85,2060.50

In [30]:
# Count unique values per column (including NaN as a value if you want)
nunique_per_col = df_TX.nunique(dropna=False)

# Get columns that have only 1 unique value
constant_cols = nunique_per_col[nunique_per_col == 1].index.tolist()
print("Dropping constant columns:", constant_cols)

# Drop those columns
df_TX = df_TX.drop(columns=constant_cols)
df_TX

Dropping constant columns: ['blane', 'diab', 'diabc', 'diabunc', 'diabwc', 'msld', 'pud', 'state_id']

,Beneficiary_ID,Submitted_HIPPS_Code,Facility_Internal_ID,Age,Gender,American_Indian_or_Alaska_Native,Asian,Black_or_African_American,Hispanic_or_Latino,Native_Hawiian_or_Pacific_Islander,White,ByDiscipline,Days_Cared_For,Agency_Medicare_Number,has_diabetes,has_heart_failure,has_hypertension,ever_deceased,ever_readmitted,BMI_Category,charlson_score,charlson_ageadj,charlson_survival_10yr,elix_quan_score,elix_quan_ageadj,elix_swiss_score,elix_swiss_ageadj,aids,alcohol,ami,canc,carit,cevd,chf,coag,copd,dane,dementia,depre,drug,fed,hp,hypc,hypothy,hypunc,ld,lymph,metacanc,obes,ond,pcd,psycho,pvd,rend,rheumd,valv,wloss,Primary_Diagnosis_ICD_10_C_M_Code_Cluster,Other_Diagnosis_Code_1_ICD_10_C_M_Cluster,Other_Diagnosis_Code_2_ICD_10_C_M_Cluster,Other_Diagnosis_Code_3_ICD_10_C_M_Cluster,Other_Diagnosis_Code_4_ICD_10_C_M_Cluster,Other_Diagnosis_Code_5_ICD_10_C_M_Cluster,COUNTY_NAME,POP_URB,POPPCT_URB,POP_RUR,POPPCT_RUR,ACS_PCT_BACHELOR_DGR,ACS_PCT_COLLEGE_ASSOCIATE_DGR,ACS_PCT_GRADUATE_DGR,ACS_PCT_HS_GRADUATE,ACS_PCT_LT_HS,ACS_PCT_NO_WORK_NO_SCHL_16_19,ACS_PCT_POSTHS_ED,ACS_PCT_VET_BACHELOR,ACS_PCT_VET_COLLEGE,ACS_PCT_VET_HS,ACS_PCT_HH_LIMIT_ENGLISH,ACS_PCT_HH_BROADBAND,ACS_PCT_HH_BROADBAND_ONLY,ACS_PCT_HH_CELLULAR,ACS_PCT_HH_CELLULAR_ONLY,ACS_PCT_HH_DIAL_INTERNET_ONLY,ACS_PCT_HH_INTERNET,ACS_PCT_HH_INTERNET_NO_SUBS,ACS_PCT_HH_NO_COMP_DEV,ACS_PCT_HH_NO_INTERNET,ACS_PCT_HH_OTHER_COMP,ACS_PCT_HH_OTHER_COMP_ONLY,ACS_PCT_HH_PC,ACS_PCT_HH_PC_ONLY,ACS_PCT_HH_SAT_INTERNET,ACS_PCT_HH_SMARTPHONE,ACS_PCT_HH_SMARTPHONE_ONLY,ACS_PCT_HH_TABLET,ACS_PCT_HH_TABLET_ONLY,ACS_PCT_CHILDREN_GRANDPARENT,ACS_PCT_CHILD_1FAM,ACS_PCT_GRANDP_NO_RESPS,ACS_PCT_GRANDP_RESPS_NO_P,ACS_PCT_GRANDP_RESPS_P,ACS_PCT_HH_1PERS,ACS_PCT_HH_ABOVE65,ACS_PCT_HH_ALONE_ABOVE65,ACS_PCT_HH_KID_1PRNT,ACS_TOT_GRANDCHILDREN_GP,ACS_PCT_HEALTH_INC_138_199,ACS_PCT_HEALTH_INC_200_399,ACS_PCT_HEALTH_INC_ABOVE400,ACS_PCT_HEALTH_INC_BELOW137,ACS_PCT_HH_1FAM_FOOD_STMP,ACS_PCT_HH_FOOD_STMP_BLW_POV,ACS_PCT_HH_NO_FD_STMP_BLW_POV,ACS_PCT_HH_PUB_ASSIST,ACS_PCT_INC50,ACS_PCT_INC50_ABOVE65,ACS_PCT_NONVET_POV_18_64,ACS_PCT_PERSON_INC_100_124,ACS_PCT_PERSON_INC_125_199,ACS_PCT_PERSON_INC_ABOVE200,ACS_PCT_PERSON_INC_BELOW99,ACS_PCT_POV_AIAN,ACS_PCT_POV_ASIAN,ACS_PCT_POV_BLACK,ACS_PCT_POV_HISPANIC,ACS_PCT_POV_MULTI,ACS_PCT_POV_NHPI,ACS_PCT_POV_OTHER,ACS_PCT_POV_WHITE,ACS_PCT_VET_POV_18_64,ACS_TOT_POP_POV
0,GGGGGGG99DzGeze,1AGKU,334582,46,Female,0,0,1,0,0,0,RN,25,677994,0,0,0,1,1,Overweight,4.0,4.0,0.53,9.0,9.0,18.0,18.0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,-1,-141,2,-1,26,0,Harris,974.0,2.81,33694.0,97.19,18.74,36.04,13.01,25.43,6.78,1.93,67.79,34.93,43.62,21.45,0.14,67.00,7.26,75.97,12.11,0.29,85.78,1.48,5.61,12.74,2.68,0.00,81.01,4.25,9.70,86.35,9.49,68.82,0.48,9.28,17.44,40.38,18.25,41.37,18.48,33.23,8.75,11.34,91.57,9.89,32.28,47.67,10.15,25.71,2.96,2.59,7.87,3.26,1.66,5.77,2.60,11.64,79.96,5.80,0.00,2.84,5.63,4.00,6.30,0.00,0.00,5.32,0.82,4868.57
1,GGGGGGG9DDWNGGz,2CGKU,487590,74,Female,0,0,0,0,0,1,RN,54,679724,0,0,0,1,0,Obese-Class1,1.0,4.0,0.53,3.0,6.0,0.0,3.0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,-1,-1,0,0,15,Dallas,21207.0,55.14,17255.0,44.86,10.55,31.23,5.93,35.91,16.39,6.05,47.70,12.59,47.37,40.04,0.17,41.62,6.05,62.78,19.32,0.42,71.66,1.71,24.33,26.64,0.71,0.00,52.24,5.98,10.36,65.98,17.08,39.02,1.33,20.11,63.60,38.75,14.84,46.41,37.27,35.58,16.68,26.69,114.24,13.87,28.33,19.23,38.58,53.60,16.20,8.89,29.97,10.93,3.44,23.83,7.73,17.35,47.56,27.36,13.45,0.00,31.53,8.72,7.27,0.00,5.88,13.49,18.04,2209.29
2,GGGGGGG9DDWWeeX,1CHKS,63847,75,Male,0,0,0,0,0,1,RN,37,679236,0,0,0,1,0,Overweight,1.0,4.0,0.53,0.0,3.0,0.0,3.0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,4,-1,-1,0,0,21,Collin,999005.0,93.85,65460.0,6.15,33.54,26.08,19.29,14.45,6.19,0.71,78.91,47.77,35.08,15.79,4.92,83.97,8.10,84.43,6.47,0.07,93.58,1.30,1.71,4.67,4.17,0.04,90.94,2.37,7.72,93.95,4.40,74.76,0.33,3.90,20.27,34.62,12.42,20.24,21.79,21.08,6.32,12.98,45.88,6.62,23.73,58.46,10.74,7.27,0.90,5.73,3.43,3.96,4.07,6.55,2.37,7.98,82.18,7.00,4.33,8.70,8.22,8.85,7.92,1.07,7.40,5.32,4.17,4546.33
3,GGGGGGG9DGXzUSG,1BHKT,10206,75,Male,0,0,0,0,0,1,RN,57,677247,0,0,0,0,0,Normal weight,0.0,3.0,0.77,0.0,3.0,0.0,3.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-1,26,0,-108,-108,-1,Lavaca,3582.0,17.61,16755.0,82.39,12.98,28.17,4.65,40.46,13.74,4.69,45.80,15.25,38.50,46.26,2.56,45.17,2.93,72.11,9.57,0.35,78.79,0.71,18.68,20.50,2.73,0.00,62.18,5.76,28.09,73.10,12.90,48.71,0.62,8.60,24.99,24.66,31.02,27.65,27.27,39.40,15.78,15.35,74.83,13.09,29.56,40.22,17.13,24.08,3.89,5.91,8.69,3.90,1.53,7.04,5.15,16.19,69.79,8.88,0.00,5.89,23.94,16.90,19.16,16.67,16.60,5.75,11.18,3268.50
4,GGGGGGG9DSUDeNG,5AGKS,17490,75,Male,0,0,0,1,0,0,RN,55,679044,0,0,0,0,0,Overweight,0.0,3.0,0.77,0.0,3.0,0.0,3.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-1,-1,-146,-1,-1,Bexar,1914732.0,95.29,94592.0,4.71,17.10,30.17,10.33,25.58,16.55,2.72,57.60,32.15,40.69,26.89,7.25,67.03,7.78,73.79,12.74,0.14,82.81,3.54,7.95,13.38,2.84,0.01,72.45,3.47,7.42,86.00,13.05,59.73,0.70,11.82,36.23,51.00,13.35,26.51,27.63,26.16,9.18,21.87,154.07,12.54,31.60,31.13,24.47,25.73,7.06,8.74,15.35,7.10,3.71,14.69,5.24,15.22,62.82,16.45,12.74,15.52,20.76,17.02,14.26,1.84,17.25,13.92,9.41,5228.28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
233268,GGGGGGXzUeSzeDG,1CHMS,696200,65,Male,0,0,0,1,0,0,RN,57,747135,0,0,0,1,0,Underweight,2.0,4.0,0.53,5.0,7.0,5.0,7.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,-1,-1,0,0,0,16,Val Verde,42680.0,89.69,4906.0,10.31,12.38,25.62,6.98,21.91,25.96,0.39,44.99,24.81,31.31,36.73,12.08,47.48,7.03,54.88,11.64,0.02,63.24,2.99,13.45,26.62,1.09,0.00,57.84,3.13,7.66,74.27,15.21,48.40,1.15,12.10,32.09,42.50,6.03,30.04,20.71,30.72,10.13,18.69,144.00,10.38,29.92,22.14,30.42,28.61,8.28,10.10,16.75,6.85,6.21,13.56,10.35,13.81,52.57,16.13,14.29,0.00,14.26,16.33,8.00,0.00,11.08,14.57,9.58,3361.21
233269,GGGGGGXzWGWNSDG,2BFLS,10291,70,Male,0,0,1,0,0,0,RN,133,458134,0,1,1,1,1,Normal weight,2.0,5.0,0.21,10.0,13.0,12.0,15.0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,0,1,Bee,14230.0,45.83,16817.0,54.17,6.92,37.87,6.15,30.88,18.18,0.57,50.94,18.93,42.30,38.77,3.38,45.78,2.96,64.04,11.25,0.07,69.22,1.64,14.92,29.14,0.54,0.00,64.86,4.16,16.94,78.98,14.34,48.77,0.68,11.54,25.63,41.49,22.88,24.52,26.93,34.45,14.15,18.60,100.22,15.65,30.82,25.71,27.83,21.76,8.59,10.83,13.88,9.79,2.12,16.97,4.80,20.03,56.53,18.64,0.00,2.31,13.30,19.54,10.98,0.00,20.19,14.24,10.25,2749.67
233270,GGGGGGXzWGzNXee,1CHKT,661333,81,Male,0,0,0,1,0,0,RN,47,743142,0,0,0,1,0,Normal weight,0.0,4.0,0.53,0.0,4.0,0.0,4.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-1,-1,-1,19,-1,7,Dallas,21207.0,55.14,17255.0,44.86,10.55,31.23,5.93,35.91,16.39,6.05,47.70,12.59,47.37,40.04,0.17,41.62,6.05,62.78,19.32,0.42,71.66,1.71,24.33,26.64,0.71,0.00,52.24,5.98,10.36,65.98,17.08,39.02,1.33,20.11,63.60,38.75,14.84,46.41,37.27,35.58,16.68,26.69,114.24,13.87,28.33,19.23,38.58,53.60,16.20,8.89,29.97,10.93,3.44,23.83,7.73,17.35,47.56,27.36,13.45,0.00,31.53,8.72,7.27,0.00,5.88,13.49,18.04,2209.29
233271,GGGGGGXzeeD99XU,1CHMT,438968,67,Female,0,0,0,0,0,1,PT,12,747241,0,0,0,1,0,Obese-Class2,0.0,2.0,0.90,0.0,2.0,0.0,2.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,27,27,10,0,0,Dallas,21207.0,55.14,17255.0,44.86,10.55,31.23,5.93,35.91,16.39,6.05,47.70,12.59,47.37,40.04,0.17,41.62,6.05,62.78,19.32,0.42,71.66,1.71,24.33,26.64,0.71,0.00,52.24,5.98,10.36,65.98,17.08,39.02,1.33,20.11,63.60,38.75,14.84,46.41,37.27,35.58,16.68,26.69,114.24,13.87,28.33,19.23,38.58,53.60,16.20,8.89,29.97,10.93,3.44,23.83,7.73,17.35,47.56,27.36,13.45,0.00,31.53,8.72,7.27,0.00,5.88,13.49,18.04,2209.29
233272,GGGGGGXzezWUUNG,1CGKT,11748,59,Female,0,0,0,1,0,0,RN,69,677285,0,0,0,1,0,Obese-Class1,0.0,1.0,0.96,0.0,1.0,0.0,1.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,-67,-67,9,0,-1,-1,Hidalgo,0.0,0.00,4178.0,100.00,13.36,29.14,6.57,33.41,17.52,10.64,49.06,23.74,32.22,44.04,5.58,46.74,7.72,62.10,14.94,0.00,73.44,4.73,15.97,21.83,0.46,0.00,60.26,4.82,15.06,76.43,19.92,47.53,0.24,11.82,28.04,36.96,63.04,0.00,26.22,37.28,12.48,18.36,50.00,9.40,38.62,18.55,33.43,44.81,13.38,8.59,21.76,5.76,6.02,23.06,8.16,12.90,57.16,21.78,27.78,0.00,100.00,21.89,11.59,0.00,3.45,15.15,9.85,2060.50

In [34]:
df_model = df_TX

In [35]:
cat_cols = ['Submitted_HIPPS_Code',
 'Facility_Internal_ID',
 'Gender',
 'ByDiscipline',
 'Agency_Medicare_Number',
 'BMI_Category',
 'Primary_Diagnosis_ICD_10_C_M_Code_Cluster',
 'Other_Diagnosis_Code_1_ICD_10_C_M_Cluster',
 'Other_Diagnosis_Code_2_ICD_10_C_M_Cluster',
 'Other_Diagnosis_Code_3_ICD_10_C_M_Cluster',
 'Other_Diagnosis_Code_4_ICD_10_C_M_Cluster',
 'Other_Diagnosis_Code_5_ICD_10_C_M_Cluster',
 'COUNTY_NAME']

# One‑hot encode only the categorical columns
df_cat_encoded = pd.get_dummies(
    df_model[cat_cols],
    drop_first=True
)

# Drop original categorical columns from df_model
df_model = df_model.drop(columns=cat_cols, errors="ignore")

# Concatenate numeric, flag, and encoded categorical columns
df_model = pd.concat([df_model, df_cat_encoded], axis=1)
df_model

,Beneficiary_ID,Age,American_Indian_or_Alaska_Native,Asian,Black_or_African_American,Hispanic_or_Latino,Native_Hawiian_or_Pacific_Islander,White,Days_Cared_For,has_diabetes,has_heart_failure,has_hypertension,ever_deceased,ever_readmitted,charlson_score,charlson_ageadj,charlson_survival_10yr,elix_quan_score,elix_quan_ageadj,elix_swiss_score,elix_swiss_ageadj,aids,alcohol,ami,canc,carit,cevd,chf,coag,copd,dane,dementia,depre,drug,fed,hp,hypc,hypothy,hypunc,ld,lymph,metacanc,obes,ond,pcd,psycho,pvd,rend,rheumd,valv,wloss,POP_URB,POPPCT_URB,POP_RUR,POPPCT_RUR,ACS_PCT_BACHELOR_DGR,ACS_PCT_COLLEGE_ASSOCIATE_DGR,ACS_PCT_GRADUATE_DGR,ACS_PCT_HS_GRADUATE,ACS_PCT_LT_HS,ACS_PCT_NO_WORK_NO_SCHL_16_19,ACS_PCT_POSTHS_ED,ACS_PCT_VET_BACHELOR,ACS_PCT_VET_COLLEGE,ACS_PCT_VET_HS,ACS_PCT_HH_LIMIT_ENGLISH,ACS_PCT_HH_BROADBAND,ACS_PCT_HH_BROADBAND_ONLY,ACS_PCT_HH_CELLULAR,ACS_PCT_HH_CELLULAR_ONLY,ACS_PCT_HH_DIAL_INTERNET_ONLY,ACS_PCT_HH_INTERNET,ACS_PCT_HH_INTERNET_NO_SUBS,ACS_PCT_HH_NO_COMP_DEV,ACS_PCT_HH_NO_INTERNET,ACS_PCT_HH_OTHER_COMP,ACS_PCT_HH_OTHER_COMP_ONLY,ACS_PCT_HH_PC,ACS_PCT_HH_PC_ONLY,ACS_PCT_HH_SAT_INTERNET,ACS_PCT_HH_SMARTPHONE,ACS_PCT_HH_SMARTPHONE_ONLY,ACS_PCT_HH_TABLET,ACS_PCT_HH_TABLET_ONLY,ACS_PCT_CHILDREN_GRANDPARENT,ACS_PCT_CHILD_1FAM,ACS_PCT_GRANDP_NO_RESPS,ACS_PCT_GRANDP_RESPS_NO_P,ACS_PCT_GRANDP_RESPS_P,ACS_PCT_HH_1PERS,ACS_PCT_HH_ABOVE65,ACS_PCT_HH_ALONE_ABOVE65,ACS_PCT_HH_KID_1PRNT,ACS_TOT_GRANDCHILDREN_GP,ACS_PCT_HEALTH_INC_138_199,ACS_PCT_HEALTH_INC_200_399,ACS_PCT_HEALTH_INC_ABOVE400,ACS_PCT_HEALTH_INC_BELOW137,ACS_PCT_HH_1FAM_FOOD_STMP,ACS_PCT_HH_FOOD_STMP_BLW_POV,ACS_PCT_HH_NO_FD_STMP_BLW_POV,ACS_PCT_HH_PUB_ASSIST,ACS_PCT_INC50,ACS_PCT_INC50_ABOVE65,ACS_PCT_NONVET_POV_18_64,ACS_PCT_PERSON_INC_100_124,ACS_PCT_PERSON_INC_125_199,ACS_PCT_PERSON_INC_ABOVE200,ACS_PCT_PERSON_INC_BELOW99,ACS_PCT_POV_AIAN,ACS_PCT_POV_ASIAN,ACS_PCT_POV_BLACK,ACS_PCT_POV_HISPANIC,ACS_PCT_POV_MULTI,ACS_PCT_POV_NHPI,ACS_PCT_POV_OTHER,ACS_PCT_POV_WHITE,ACS_PCT_VET_POV_18_64,ACS_TOT_POP_POV,Facility_Internal_ID,Agency_Medicare_Number,Primary_Diagnosis_ICD_10_C_M_Code_Cluster,Other_Diagnosis_Code_1_ICD_10_C_M_Cluster,Other_Diagnosis_Code_2_ICD_10_C_M_Cluster,Other_Diagnosis_Code_3_ICD_10_C_M_Cluster,Other_Diagnosis_Code_4_ICD_10_C_M_Cluster,Other_Diagnosis_Code_5_ICD_10_C_M_Cluster,Submitted_HIPPS_Code_1AFK2,Submitted_HIPPS_Code_1AFKS,Submitted_HIPPS_Code_1AFKT,Submitted_HIPPS_Code_1AFKU,Submitted_HIPPS_Code_1AFKV,Submitted_HIPPS_Code_1AFLS,Submitted_HIPPS_Code_1AFLT,Submitted_HIPPS_Code_1AFLU,Submitted_HIPPS_Code_1AFMS,Submitted_HIPPS_Code_1AFMT,Submitted_HIPPS_Code_1AFMU,Submitted_HIPPS_Code_1AFMV,Submitted_HIPPS_Code_1AFNS,Submitted_HIPPS_Code_1AFNT,Submitted_HIPPS_Code_1AFPS,Submitted_HIPPS_Code_1AFPT,Submitted_HIPPS_Code_1AFPU,Submitted_HIPPS_Code_1AGK1,Submitted_HIPPS_Code_1AGKS,Submitted_HIPPS_Code_1AGKT,Submitted_HIPPS_Code_1AGKU,Submitted_HIPPS_Code_1AGKV,Submitted_HIPPS_Code_1AGLS,Submitted_HIPPS_Code_1AGLT,Submitted_HIPPS_Code_1AGLU,Submitted_HIPPS_Code_1AGLV,Submitted_HIPPS_Code_1AGM1,Submitted_HIPPS_Code_1AGMS,Submitted_HIPPS_Code_1AGMT,Submitted_HIPPS_Code_1AGMU,Submitted_HIPPS_Code_1AGMV,Submitted_HIPPS_Code_1AGNS,Submitted_HIPPS_Code_1AGNT,Submitted_HIPPS_Code_1AGNU,Submitted_HIPPS_Code_1AGNV,Submitted_HIPPS_Code_1AGPS,Submitted_HIPPS_Code_1AGPT,Submitted_HIPPS_Code_1AGPU,Submitted_HIPPS_Code_1AGPV,Submitted_HIPPS_Code_1AHK1,Submitted_HIPPS_Code_1AHK2,Submitted_HIPPS_Code_1AHKS,Submitted_HIPPS_Code_1AHKT,Submitted_HIPPS_Code_1AHKU,Submitted_HIPPS_Code_1AHKV,Submitted_HIPPS_Code_1AHKW,Submitted_HIPPS_Code_1AHLS,Submitted_HIPPS_Code_1AHLT,Submitted_HIPPS_Code_1AHLU,Submitted_HIPPS_Code_1AHMS,Submitted_HIPPS_Code_1AHMT,Submitted_HIPPS_Code_1AHMU,Submitted_HIPPS_Code_1AHMV,Submitted_HIPPS_Code_1AHNS,Submitted_HIPPS_Code_1AHNT,Submitted_HIPPS_Code_1AHNU,Submitted_HIPPS_Code_1AHNV,Submitted_HIPPS_Code_1AHNW,Submitted_HIPPS_Code_1AHPS,Submitted_HIPPS_Code_1AHPT,Submitted_HIPPS_Code_1AHPU,Submitted_HIPPS_Code_1AHPV,Submitted_HIPPS_Code_1BFKS,Submitted_HIPPS_Code_1BFKT,Submitted_HIPPS_Code_1BFKU,Submitted_HIPPS_Code_1BFKV,Submitted_HIPPS_Code_1BFLS,Submitted_HIPPS_Code_1BFLT,Submitted_HIPPS_Code_1BFLU,Submitted_HIPPS_Code_1BFLV,Submitted_HIPPS_Code_1BFMS,Submitted_HIPPS_Code_1BFMT,Submitted_HIPPS_Code_1BFMU,Submitted_HIPPS_Code_1BFMV,Submitted_HIPPS_Code_1BFNS,Submitted_HIPPS_Code_1BFNT,Submitted_HIPPS_Code_1BFNU,Submitted_HIPPS_Code_1BFPS,Submitted_HIPPS_Code_1BFPT,Submitted_HIPPS_Code_1BFPU,Submitted_HIPPS_Code_1BFPV,Submitted_HIPPS_Code_1BGK1,Submitted_HIPPS_Code_1BGK2,Submitted_HIPPS_Code_1BGKS,Submitted_HIPPS_Code_1BGKT,Submitted_HIPPS_Code_1BGKU,Submitted_HIPPS_Code_1BGKV,Submitted_HIPPS_Code_1BGKW,Submitted_HIPPS_Code_1BGLS,Submitted_HIPPS_Code_1BGLT,Submitted_HIPPS_Code_1BGLU,Submitted_HIPPS_Code_1BGLV,Submitted_HIPPS_Code_1BGM1,Submitted_HIPPS_Code_1BGMS,Submitted_HIPPS_Code_1BGMT,Submitted_HIPPS_Code_1BGMU,Submitted_HIPPS_Code_1BGMV,Submitted_HIPPS_Code_1BGNS,Submitted_HIPPS_Code_1BGNT,Submitted_HIPPS_Code_1BGNU,Submitted_HIPPS_Code_1BGNV,Submitted_HIPPS_Code_1BGP1,Submitted_HIPPS_Code_1BGPS,Submitted_HIPPS_Code_1BGPT,Submitted_HIPPS_Code_1BGPU,Submitted_HIPPS_Code_1BGPV,Submitted_HIPPS_Code_1BHK1,Submitted_HIPPS_Code_1BHKS,Submitted_HIPPS_Code_1BHKT,Submitted_HIPPS_Code_1BHKU,Submitted_HIPPS_Code_1BHKV,Submitted_HIPPS_Code_1BHKW,Submitted_HIPPS_Code_1BHLS,Submitted_HIPPS_Code_1BHLT,Submitted_HIPPS_Code_1BHLU,Submitted_HIPPS_Code_1BHLV,Submitted_HIPPS_Code_1BHMS,Submitted_HIPPS_Code_1BHMT,Submitted_HIPPS_Code_1BHMU,Submitted_HIPPS_Code_1BHMV,Submitted_HIPPS_Code_1BHN1,Submitted_HIPPS_Code_1BHNS,Submitted_HIPPS_Code_1BHNT,Submitted_HIPPS_Code_1BHNU,Submitted_HIPPS_Code_1BHNV,Submitted_HIPPS_Code_1BHPS,Submitted_HIPPS_Code_1BHPT,Submitted_HIPPS_Code_1BHPU,Submitted_HIPPS_Code_1BHPV,Submitted_HIPPS_Code_1BHPW,Submitted_HIPPS_Code_1CFK1,Submitted_HIPPS_Code_1CFKS,Submitted_HIPPS_Code_1CFKT,Submitted_HIPPS_Code_1CFKU,Submitted_HIPPS_Code_1CFKV,Submitted_HIPPS_Code_1CFKW,Submitted_HIPPS_Code_1CFKX,Submitted_HIPPS_Code_1CFLS,Submitted_HIPPS_Code_1CFLT,Submitted_HIPPS_Code_1CFLU,Submitted_HIPPS_Code_1CFLV,Submitted_HIPPS_Code_1CFLW,Submitted_HIPPS_Code_1CFMS,Submitted_HIPPS_Code_1CFMT,Submitted_HIPPS_Code_1CFMU,Submitted_HIPPS_Code_1CFMV,Submitted_HIPPS_Code_1CFMW,Submitted_HIPPS_Code_1CFNS,Submitted_HIPPS_Code_1CFNT,Submitted_HIPPS_Code_1CFNU,Submitted_HIPPS_Code_1CFNV,Submitted_HIPPS_Code_1CFNW,Submitted_HIPPS_Code_1CFPS,Submitted_HIPPS_Code_1CFPT,Submitted_HIPPS_Code_1CFPU,Submitted_HIPPS_Code_1CFPV,Submitted_HIPPS_Code_1CFPW,Submitted_HIPPS_Code_1CFPX,Submitted_HIPPS_Code_1CGK1,Submitted_HIPPS_Code_1CGKS,Submitted_HIPPS_Code_1CGKT,Submitted_HIPPS_Code_1CGKU,Submitted_HIPPS_Code_1CGKV,Submitted_HIPPS_Code_1CGKW,Submitted_HIPPS_Code_1CGKX,Submitted_HIPPS_Code_1CGL1,Submitted_HIPPS_Code_1CGLS,Submitted_HIPPS_Code_1CGLT,Submitted_HIPPS_Code_1CGLU,Submitted_HIPPS_Code_1CGLV,Submitted_HIPPS_Code_1CGLW,Submitted_HIPPS_Code_1CGMS,Submitted_HIPPS_Code_1CGMT,Submitted_HIPPS_Code_1CGMU,Submitted_HIPPS_Code_1CGMV,Submitted_HIPPS_Code_1CGMW,Submitted_HIPPS_Code_1CGNS,Submitted_HIPPS_Code_1CGNT,Submitted_HIPPS_Code_1CGNU,Submitted_HIPPS_Code_1CGNV,Submitted_HIPPS_Code_1CGNW,Submitted_HIPPS_Code_1CGPS,Submitted_HIPPS_Code_1CGPT,Submitted_HIPPS_Code_1CGPU,Submitted_HIPPS_Code_1CGPV,Submitted_HIPPS_Code_1CGPW,Submitted_HIPPS_Code_1CGPX,Submitted_HIPPS_Code_1CHK1,Submitted_HIPPS_Code_1CHK5,Submitted_HIPPS_Code_1CHKS,Submitted_HIPPS_Code_1CHKT,Submitted_HIPPS_Code_1CHKU,Submitted_HIPPS_Code_1CHKV,Submitted_HIPPS_Code_1CHKW,Submitted_HIPPS_Code_1CHKX,Submitted_HIPPS_Code_1CHLS,Submitted_HIPPS_Code_1CHLT,Submitted_HIPPS_Code_1CHLU,Submitted_HIPPS_Code_1CHLV,Submitted_HIPPS_Code_1CHLW,Submitted_HIPPS_Code_1CHLX,Submitted_HIPPS_Code_1CHM1,Submitted_HIPPS_Code_1CHM3,Submitted_HIPPS_Code_1CHMS,Submitted_HIPPS_Code_1CHMT,Submitted_HIPPS_Code_1CHMU,Submitted_HIPPS_Code_1CHMV,Submitted_HIPPS_Code_1CHMW,Submitted_HIPPS_Code_1CHMX,Submitted_HIPPS_Code_1CHNS,Submitted_HIPPS_Code_1CHNT,Submitted_HIPPS_Code_1CHNU,Submitted_HIPPS_Code_1CHNV,Submitted_HIPPS_Code_1CHNW,Submitted_HIPPS_Code_1CHNX,Submitted_HIPPS_Code_1CHPS,Submitted_HIPPS_Code_1CHPT,Submitted_HIPPS_Code_1CHPU,Submitted_HIPPS_Code_1CHPV,Submitted_HIPPS_Code_1CHPW,Submitted_HIPPS_Code_1CHPX,Submitted_HIPPS_Code_2AFKS,Submitted_HIPPS_Code_2AFKT,Submitted_HIPPS_Code_2AFKU,Submitted_HIPPS_Code_2AFKV,Submitted_HIPPS_Code_2AFLS,Submitted_HIPPS_Code_2AFLT,Submitted_HIPPS_Code_2AFLU,Submitted_HIPPS_Code_2AFMS,Submitted_HIPPS_Code_2AFMT,Submitted_HIPPS_Code_2AFMU,Submitted_HIPPS_Code_2AFMV,Submitted_HIPPS_Code_2AGKS,Submitted_HIPPS_Code_2AGKT,Submitted_HIPPS_Code_2AGKU,Submitted_HIPPS_Code_2AGKV,Submitted_HIPPS_Code_2AGLS,Submitted_HIPPS_Code_2AGLT,Submitted_HIPPS_Code_2AGLU,Submitted_HIPPS_Code_2AGMS,Submitted_HIPPS_Code_2AGMT,Submitted_HIPPS_Code_2AGMU,Submitted_HIPPS_Code_2AHKS,Submitted_HIPPS_Code_2AHKT,Submitted_HIPPS_Code_2AHKU,Submitted_HIPPS_Code_2AHLS,Submitted_HIPPS_Code_2AHLT,Submitted_HIPPS_Code_2AHLU,Submitted_HIPPS_Code_2AHMS,Submitted_HIPPS_Code_2AHMT,Submitted_HIPPS_Code_2AHMU,Submitted_HIPPS_Code_2BFKS,Submitted_HIPPS_Code_2BFKT,Submitted_HIPPS_Code_2BFKU,Submitted_HIPPS_Code_2BFKV,Submitted_HIPPS_Code_2BFLS,Submitted_HIPPS_Code_2BFLT,Submitted_HIPPS_Code_2BFLU,Submitted_HIPPS_Code_2BFLV,Submitted_HIPPS_Code_2BFLW,Submitted_HIPPS_Code_2BFM2,Submitted_HIPPS_Code_2BFMS,Submitted_HIPPS_Code_2BFMT,Submitted_HIPPS_Code_2BFMU,Submitted_HIPPS_Code_2BGKS,Submitted_HIPPS_Code_2BGKT,Submitted_HIPPS_Code_2BGKU,Submitted_HIPPS_Code_2BGKV,Submitted_HIPPS_Code_2BGKW,Submitted_HIPPS_Code_2BGLS,Submitted_HIPPS_Code_2BGLT,Submitted_HIPPS_Code_2BGLU,Submitted_HIPPS_Code_2BGLV,Submitted_HIPPS_Code_2BGMS,Submitted_HIPPS_Code_2BGMT,Submitted_HIPPS_Code_2BGMU,Submitted_HIPPS_Code_2BGMV,Submitted_HIPPS_Code_2BHKS,Submitted_HIPPS_Code_2BHKT,Submitted_HIPPS_Code_2BHKU,Submitted_HIPPS_Code_2BHKV,Submitted_HIPPS_Code_2BHLS,Submitted_HIPPS_Code_2BHLT,Submitted_HIPPS_Code_2BHLU,Submitted_HIPPS_Code_2BHLV,Submitted_HIPPS_Code_2BHMS,Submitted_HIPPS_Code_2BHMT,Submitted_HIPPS_Code_2BHMU,Submitted_HIPPS_Code_2BHMV,Submitted_HIPPS_Code_2CFKS,Submitted_HIPPS_Code_2CFKT,Submitted_HIPPS_Code_2CFKU,Submitted_HIPPS_Code_2CFKV,Submitted_HIPPS_Code_2CFKW,Submitted_HIPPS_Code_2CFKX,Submitted_HIPPS_Code_2CFLS,Submitted_HIPPS_Code_2CFLT,Submitted_HIPPS_Code_2CFLU,Submitted_HIPPS_Code_2CFLV,Submitted_HIPPS_Code_2CFLW,Submitted_HIPPS_Code_2CFLX,Submitted_HIPPS_Code_2CFMS,Submitted_HIPPS_Code_2CFMT,Submitted_HIPPS_Code_2CFMU,Submitted_HIPPS_Code_2CFMV,Submitted_HIPPS_Code_2CFMW,Submitted_HIPPS_Code_2CFMX,Submitted_HIPPS_Code_2CGKS,Submitted_HIPPS_Code_2CGKT,Submitted_HIPPS_Code_2CGKU,Submitted_HIPPS_Code_2CGKV,Submitted_HIPPS_Code_2CGKW,Submitted_HIPPS_Code_2CGKX,Submitted_HIPPS_Code_2CGL1,Submitted_HIPPS_Code_2CGLS,Submitted_HIPPS_Code_2CGLT,Submitted_HIPPS_Code_2CGLU,Submitted_HIPPS_Code_2CGLV,Submitted_HIPPS_Code_2CGLW,Submitted_HIPPS_Code_2CGLX,Submitted_HIPPS_Code_2CGMS,Submitted_HIPPS_Code_2CGMT,Submitted_HIPPS_Code_2CGMU,Submitted_HIPPS_Code_2CGMV,Submitted_HIPPS_Code_2CGMW,Submitted_HIPPS_Code_2CGMX,Submitted_HIPPS_Code_2CHKS,Submitted_HIPPS_Code_2CHKT,Submitted_HIPPS_Code_2CHKU,Submitted_HIPPS_Code_2CHKV,Submitted_HIPPS_Code_2CHKW,Submitted_HIPPS_Code_2CHKX,Submitted_HIPPS_Code_2CHLS,Submitted_HIPPS_Code_2CHLT,Submitted_HIPPS_Code_2CHLU,Submitted_HIPPS_Code_2CHLV,Submitted_HIPPS_Code_2CHLW,Submitted_HIPPS_Code_2CHLX,Submitted_HIPPS_Code_2CHMS,Submitted_HIPPS_Code_2CHMT,Submitted_HIPPS_Code_2CHMU,Submitted_HIPPS_Code_2CHMV,Submitted_HIPPS_Code_2CHMW,Submitted_HIPPS_Code_2CHMX,Submitted_HIPPS_Code_3AFKS,Submitted_HIPPS_Code_3AFKT,Submitted_HIPPS_Code_3AFKU,Submitted_HIPPS_Code_3AFLS,Submitted_HIPPS_Code_3AFMS,Submitted_HIPPS_Code_3AFNS,Submitted_HIPPS_Code_3AFNT,Submitted_HIPPS_Code_3AFPS,Submitted_HIPPS_Code_3AFPT,Submitted_HIPPS_Code_3AGKS,Submitted_HIPPS_Code_3AGKT,Submitted_HIPPS_Code_3AGKU,Submitted_HIPPS_Code_3AGKV,Submitted_HIPPS_Code_3AGLS,Submitted_HIPPS_Code_3AGMS,Submitted_HIPPS_Code_3AGMT,Submitted_HIPPS_Code_3AGMU,Submitted_HIPPS_Code_3AGNS,Submitted_HIPPS_Code_3AGPS,Submitted_HIPPS_Code_3AGPT,Submitted_HIPPS_Code_3AHKS,Submitted_HIPPS_Code_3AHKT,Submitted_HIPPS_Code_3AHKU,Submitted_HIPPS_Code_3AHLS,Submitted_HIPPS_Code_3AHLT,Submitted_HIPPS_Code_3AHMS,Submitted_HIPPS_Code_3AHMT,Submitted_HIPPS_Code_3AHMU,Submitted_HIPPS_Code_3AHNS,Submitted_HIPPS_Code_3AHNT,Submitted_HIPPS_Code_3AHPS,Submitted_HIPPS_Code_3AHPT,Submitted_HIPPS_Code_3AHPU,Submitted_HIPPS_Code_3BFKS,Submitted_HIPPS_Code_3BFKT,Submitted_HIPPS_Code_3BFKU,Submitted_HIPPS_Code_3BFLS,Submitted_HIPPS_Code_3BFMS,Submitted_HIPPS_Code_3BFNS,Submitted_HIPPS_Code_3BFNT,Submitted_HIPPS_Code_3BFPS,Submitted_HIPPS_Code_3BGKS,Submitted_HIPPS_Code_3BGKT,Submitted_HIPPS_Code_3BGKU,Submitted_HIPPS_Code_3BGLS,Submitted_HIPPS_Code_3BGMS,Submitted_HIPPS_Code_3BGMT,Submitted_HIPPS_Code_3BGMU,Submitted_HIPPS_Code_3BGNS,Submitted_HIPPS_Code_3BGPS,Submitted_HIPPS_Code_3BGPT,Submitted_HIPPS_Code_3BGPU,Submitted_HIPPS_Code_3BHKS,Submitted_HIPPS_Code_3BHKT,Submitted_HIPPS_Code_3BHKU,Submitted_HIPPS_Code_3BHKV,Submitted_HIPPS_Code_3BHLS,Submitted_HIPPS_Code_3BHLT,Submitted_HIPPS_Code_3BHMS,Submitted_HIPPS_Code_3BHMT,Submitted_HIPPS_Code_3BHMU,Submitted_HIPPS_Code_3BHNS,Submitted_HIPPS_Code_3BHNT,Submitted_HIPPS_Code_3BHNU,Submitted_HIPPS_Code_3BHNV,Submitted_HIPPS_Code_3BHPS,Submitted_HIPPS_Code_3BHPT,Submitted_HIPPS_Code_3BHPU,Submitted_HIPPS_Code_3CFKS,Submitted_HIPPS_Code_3CFKT,Submitted_HIPPS_Code_3CFKU,Submitted_HIPPS_Code_3CFKV,Submitted_HIPPS_Code_3CFKW,Submitted_HIPPS_Code_3CFKX,Submitted_HIPPS_Code_3CFMT,Submitted_HIPPS_Code_3CFNS,Submitted_HIPPS_Code_3CFNU,Submitted_HIPPS_Code_3CFPS,Submitted_HIPPS_Code_3CFPV,Submitted_HIPPS_Code_3CGK1,Submitted_HIPPS_Code_3CGKS,Submitted_HIPPS_Code_3CGKT,Submitted_HIPPS_Code_3CGKU,Submitted_HIPPS_Code_3CGKV,Submitted_HIPPS_Code_3CGKW,Submitted_HIPPS_Code_3CGLS,Submitted_HIPPS_Code_3CGLT,Submitted_HIPPS_Code_3CGLU,Submitted_HIPPS_Code_3CGLV,Submitted_HIPPS_Code_3CGMS,Submitted_HIPPS_Code_3CGMT,Submitted_HIPPS_Code_3CGMU,Submitted_HIPPS_Code_3CGMV,Submitted_HIPPS_Code_3CGMW,Submitted_HIPPS_Code_3CGNS,Submitted_HIPPS_Code_3CGNT,Submitted_HIPPS_Code_3CGNU,Submitted_HIPPS_Code_3CGNV,Submitted_HIPPS_Code_3CGNW,Submitted_HIPPS_Code_3CGPS,Submitted_HIPPS_Code_3CGPT,Submitted_HIPPS_Code_3CGPU,Submitted_HIPPS_Code_3CGPV,Submitted_HIPPS_Code_3CGPW,Submitted_HIPPS_Code_3CHKS,Submitted_HIPPS_Code_3CHKT,Submitted_HIPPS_Code_3CHKU,Submitted_HIPPS_Code_3CHKV,Submitted_HIPPS_Code_3CHKW,Submitted_HIPPS_Code_3CHKX,Submitted_HIPPS_Code_3CHLS,Submitted_HIPPS_Code_3CHLT,Submitted_HIPPS_Code_3CHLU,Submitted_HIPPS_Code_3CHLV,Submitted_HIPPS_Code_3CHMS,Submitted_HIPPS_Code_3CHMT,Submitted_HIPPS_Code_3CHMU,Submitted_HIPPS_Code_3CHMV,Submitted_HIPPS_Code_3CHMW,Submitted_HIPPS_Code_3CHNS,Submitted_HIPPS_Code_3CHNT,Submitted_HIPPS_Code_3CHNU,Submitted_HIPPS_Code_3CHNV,Submitted_HIPPS_Code_3CHNW,Submitted_HIPPS_Code_3CHPS,Submitted_HIPPS_Code_3CHPT,Submitted_HIPPS_Code_3CHPU,Submitted_HIPPS_Code_3CHPV,Submitted_HIPPS_Code_3CHPW,Submitted_HIPPS_Code_3CHPX,Submitted_HIPPS_Code_4AFKS,Submitted_HIPPS_Code_4AFLS,Submitted_HIPPS_Code_4AFMS,Submitted_HIPPS_Code_4AGKS,Submitted_HIPPS_Code_4AGKT,Submitted_HIPPS_Code_4AGKU,Submitted_HIPPS_Code_4AGLS,Submitted_HIPPS_Code_4AGLT,Submitted_HIPPS_Code_4AGLU,Submitted_HIPPS_Code_4AGMS,Submitted_HIPPS_Code_4AGMT,Submitted_HIPPS_Code_4AHKS,Submitted_HIPPS_Code_4AHKT,Submitted_HIPPS_Code_4AHLS,Submitted_HIPPS_Code_4AHMS,Submitted_HIPPS_Code_4AHMT,Submitted_HIPPS_Code_4BFKS,Submitted_HIPPS_Code_4BFLS,Submitted_HIPPS_Code_4BFLU,Submitted_HIPPS_Code_4BFMS,Submitted_HIPPS_Code_4BGKS,Submitted_HIPPS_Code_4BGKT,Submitted_HIPPS_Code_4BGKU,Submitted_HIPPS_Code_4BGLS,Submitted_HIPPS_Code_4BGLT,Submitted_HIPPS_Code_4BGLU,Submitted_HIPPS_Code_4BGMS,Submitted_HIPPS_Code_4BGMT,Submitted_HIPPS_Code_4BGMU,Submitted_HIPPS_Code_4BGMV,Submitted_HIPPS_Code_4BHKS,Submitted_HIPPS_Code_4BHKT,Submitted_HIPPS_Code_4BHKU,Submitted_HIPPS_Code_4BHLS,Submitted_HIPPS_Code_4BHLT,Submitted_HIPPS_Code_4BHMS,Submitted_HIPPS_Code_4BHMT,Submitted_HIPPS_Code_4BHMU,Submitted_HIPPS_Code_4CFKT,Submitted_HIPPS_Code_4CFLT,Submitted_HIPPS_Code_4CFLV,Submitted_HIPPS_Code_4CGKS,Submitted_HIPPS_Code_4CGKT,Submitted_HIPPS_Code_4CGKU,Submitted_HIPPS_Code_4CGKV,Submitted_HIPPS_Code_4CGKW,Submitted_HIPPS_Code_4CGLS,Submitted_HIPPS_Code_4CGLT,Submitted_HIPPS_Code_4CGLU,Submitted_HIPPS_Code_4CGLV,Submitted_HIPPS_Code_4CGLW,Submitted_HIPPS_Code_4CGMS,Submitted_HIPPS_Code_4CGMT,Submitted_HIPPS_Code_4CGMU,Submitted_HIPPS_Code_4CGMV,Submitted_HIPPS_Code_4CGMW,Submitted_HIPPS_Code_4CHKS,Submitted_HIPPS_Code_4CHKT,Submitted_HIPPS_Code_4CHKU,Submitted_HIPPS_Code_4CHKV,Submitted_HIPPS_Code_4CHKW,Submitted_HIPPS_Code_4CHKX,Submitted_HIPPS_Code_4CHLS,Submitted_HIPPS_Code_4CHLT,Submitted_HIPPS_Code_4CHLU,Submitted_HIPPS_Code_4CHLV,Submitted_HIPPS_Code_4CHLW,Submitted_HIPPS_Code_4CHLX,Submitted_HIPPS_Code_4CHMS,Submitted_HIPPS_Code_4CHMT,Submitted_HIPPS_Code_4CHMU,Submitted_HIPPS_Code_4CHMV,Submitted_HIPPS_Code_4CHMW,Submitted_HIPPS_Code_5AFKS,Submitted_HIPPS_Code_5AFKT,Submitted_HIPPS_Code_5AFKU,Submitted_HIPPS_Code_5AGK1,Submitted_HIPPS_Code_5AGKS,Submitted_HIPPS_Code_5AGKT,Submitted_HIPPS_Code_5AGKU,Submitted_HIPPS_Code_5AHKS,Submitted_HIPPS_Code_5AHKT,Submitted_HIPPS_Code_5AHKU,Submitted_HIPPS_Code_5AHKV,Submitted_HIPPS_Code_5BFKS,Submitted_HIPPS_Code_5BFKT,Submitted_HIPPS_Code_5BFKU,Submitted_HIPPS_Code_5BGKS,Submitted_HIPPS_Code_5BGKT,Submitted_HIPPS_Code_5BGKU,Submitted_HIPPS_Code_5BGKV,Submitted_HIPPS_Code_5BGKW,Submitted_HIPPS_Code_5BHKS,Submitted_HIPPS_Code_5BHKT,Submitted_HIPPS_Code_5BHKU,Submitted_HIPPS_Code_5BHKV,Submitted_HIPPS_Code_5BHKW,Submitted_HIPPS_Code_5CFKS,Submitted_HIPPS_Code_5CFKT,Submitted_HIPPS_Code_5CFKU,Submitted_HIPPS_Code_5CFKV,Submitted_HIPPS_Code_5CFKW,Submitted_HIPPS_Code_5CGKS,Submitted_HIPPS_Code_5CGKT,Submitted_HIPPS_Code_5CGKU,Submitted_HIPPS_Code_5CGKV,Submitted_HIPPS_Code_5CGKW,Submitted_HIPPS_Code_5CGKX,Submitted_HIPPS_Code_5CHKS,Submitted_HIPPS_Code_5CHKT,Submitted_HIPPS_Code_5CHKU,Submitted_HIPPS_Code_5CHKV,Submitted_HIPPS_Code_5CHKW,Submitted_HIPPS_Code_5CHKX,Gender_Male,ByDiscipline_PT,ByDiscipline_RN,ByDiscipline_SLP/ST,BMI_Category_Obese-Class1,BMI_Category_Obese-Class2,BMI_Category_Obese-Class3,BMI_Category_Overweight,BMI_Category_Underweight,COUNTY_NAME_Andrews,COUNTY_NAME_Angelina,COUNTY_NAME_Aransas,COUNTY_NAME_Archer,COUNTY_NAME_Armstrong,COUNTY_NAME_Atascosa,COUNTY_NAME_Austin,COUNTY_NAME_Bailey,COUNTY_NAME_Bandera,COUNTY_NAME_Bastrop,COUNTY_NAME_Baylor,COUNTY_NAME_Bee,COUNTY_NAME_Bell,COUNTY_NAME_Bexar,COUNTY_NAME_Blanco,COUNTY_NAME_Borden,COUNTY_NAME_Bosque,COUNTY_NAME_Bowie,COUNTY_NAME_Brazoria,COUNTY_NAME_Brazos,COUNTY_NAME_Brewster,COUNTY_NAME_Briscoe,COUNTY_NAME_Brooks,COUNTY_NAME_Brown,COUNTY_NAME_Burleson,COUNTY_NAME_Burnet,COUNTY_NAME_Caldwell,COUNTY_NAME_Calhoun,COUNTY_NAME_Callahan,COUNTY_NAME_Cameron,COUNTY_NAME_Camp,COUNTY_NAME_Carson,COUNTY_NAME_Cass,COUNTY_NAME_Castro,COUNTY_NAME_Chambers,COUNTY_NAME_Cherokee,COUNTY_NAME_Childress,COUNTY_NAME_Clay,COUNTY_NAME_Cochran,COUNTY_NAME_Coke,COUNTY_NAME_Coleman,COUNTY_NAME_Collin,COUNTY_NAME_Collingsworth,COUNTY_NAME_Colorado,COUNTY_NAME_Comal,COUNTY_NAME_Comanche,COUNTY_NAME_Concho,COUNTY_NAME_Cooke,COUNTY_NAME_Coryell,COUNTY_NAME_Cottle,COUNTY_NAME_Crane,COUNTY_NAME_Crockett,COUNTY_NAME_Crosby,COUNTY_NAME_Culberson,COUNTY_NAME_Dallam,COUNTY_NAME_Dallas,COUNTY_NAME_Dawson,COUNTY_NAME_DeWitt,COUNTY_NAME_Deaf Smith,COUNTY_NAME_Delta,COUNTY_NAME_Denton,COUNTY_NAME_Dickens,COUNTY_NAME_Dimmit,COUNTY_NAME_Donley,COUNTY_NAME_Duval,COUNTY_NAME_Eastland,COUNTY_NAME_Ector,COUNTY_NAME_Edwards,COUNTY_NAME_El Paso,COUNTY_NAME_Ellis,COUNTY_NAME_Erath,COUNTY_NAME_Falls,COUNTY_NAME_Fannin,COUNTY_NAME_Fayette,COUNTY_NAME_Fisher,COUNTY_NAME_Floyd,COUNTY_NAME_Foard,COUNTY_NAME_Fort Bend,COUNTY_NAME_Franklin,COUNTY_NAME_Freestone,COUNTY_NAME_Frio,COUNTY_NAME_Gaines,COUNTY_NAME_Galveston,COUNTY_NAME

In [36]:
target = "ever_readmitted"

# Drop Beneficiary_ID and non-numeric; corr uses only numeric columns by default
df_corr = df_model.drop(columns=["Beneficiary_ID"], errors="ignore")

corr_with_target = df_corr.corr(numeric_only=True)[target].drop(labels=[target])
corr_with_target_sorted = corr_with_target.reindex(
    corr_with_target.abs().sort_values(ascending=False).index
)

threshold = 0.6
high_corr = corr_with_target_sorted[ corr_with_target_sorted.abs() > threshold ]
high_corr

Series([], Name: ever_readmitted, dtype: float64)

In [39]:
# Make a copy to avoid side effects
df_corr = df_model.copy()

# Drop Beneficiary_ID if present
df_corr = df_corr.drop(columns=["Beneficiary_ID"], errors="ignore")

# Ensure only numeric columns are used (corr ignores non-numeric by default)
corr_matrix = df_corr.corr(numeric_only=True)
corr_matrix

,Age,American_Indian_or_Alaska_Native,Asian,Black_or_African_American,Hispanic_or_Latino,Native_Hawiian_or_Pacific_Islander,White,Days_Cared_For,has_diabetes,has_heart_failure,has_hypertension,ever_deceased,ever_readmitted,charlson_score,charlson_ageadj,charlson_survival_10yr,elix_quan_score,elix_quan_ageadj,elix_swiss_score,elix_swiss_ageadj,aids,alcohol,ami,canc,carit,cevd,chf,coag,copd,dane,dementia,depre,drug,fed,hp,hypc,hypothy,hypunc,ld,lymph,metacanc,obes,ond,pcd,psycho,pvd,rend,rheumd,valv,wloss,POP_URB,POPPCT_URB,POP_RUR,POPPCT_RUR,ACS_PCT_BACHELOR_DGR,ACS_PCT_COLLEGE_ASSOCIATE_DGR,ACS_PCT_GRADUATE_DGR,ACS_PCT_HS_GRADUATE,ACS_PCT_LT_HS,ACS_PCT_NO_WORK_NO_SCHL_16_19,ACS_PCT_POSTHS_ED,ACS_PCT_VET_BACHELOR,ACS_PCT_VET_COLLEGE,ACS_PCT_VET_HS,ACS_PCT_HH_LIMIT_ENGLISH,ACS_PCT_HH_BROADBAND,ACS_PCT_HH_BROADBAND_ONLY,ACS_PCT_HH_CELLULAR,ACS_PCT_HH_CELLULAR_ONLY,ACS_PCT_HH_DIAL_INTERNET_ONLY,ACS_PCT_HH_INTERNET,ACS_PCT_HH_INTERNET_NO_SUBS,ACS_PCT_HH_NO_COMP_DEV,ACS_PCT_HH_NO_INTERNET,ACS_PCT_HH_OTHER_COMP,ACS_PCT_HH_OTHER_COMP_ONLY,ACS_PCT_HH_PC,ACS_PCT_HH_PC_ONLY,ACS_PCT_HH_SAT_INTERNET,ACS_PCT_HH_SMARTPHONE,ACS_PCT_HH_SMARTPHONE_ONLY,ACS_PCT_HH_TABLET,ACS_PCT_HH_TABLET_ONLY,ACS_PCT_CHILDREN_GRANDPARENT,ACS_PCT_CHILD_1FAM,ACS_PCT_GRANDP_NO_RESPS,ACS_PCT_GRANDP_RESPS_NO_P,ACS_PCT_GRANDP_RESPS_P,ACS_PCT_HH_1PERS,ACS_PCT_HH_ABOVE65,ACS_PCT_HH_ALONE_ABOVE65,ACS_PCT_HH_KID_1PRNT,ACS_TOT_GRANDCHILDREN_GP,ACS_PCT_HEALTH_INC_138_199,ACS_PCT_HEALTH_INC_200_399,ACS_PCT_HEALTH_INC_ABOVE400,ACS_PCT_HEALTH_INC_BELOW137,ACS_PCT_HH_1FAM_FOOD_STMP,ACS_PCT_HH_FOOD_STMP_BLW_POV,ACS_PCT_HH_NO_FD_STMP_BLW_POV,ACS_PCT_HH_PUB_ASSIST,ACS_PCT_INC50,ACS_PCT_INC50_ABOVE65,ACS_PCT_NONVET_POV_18_64,ACS_PCT_PERSON_INC_100_124,ACS_PCT_PERSON_INC_125_199,ACS_PCT_PERSON_INC_ABOVE200,ACS_PCT_PERSON_INC_BELOW99,ACS_PCT_POV_AIAN,ACS_PCT_POV_ASIAN,ACS_PCT_POV_BLACK,ACS_PCT_POV_HISPANIC,ACS_PCT_POV_MULTI,ACS_PCT_POV_NHPI,ACS_PCT_POV_OTHER,ACS_PCT_POV_WHITE,ACS_PCT_VET_POV_18_64,ACS_TOT_POP_POV,Facility_Internal_ID,Agency_Medicare_Number,Primary_Diagnosis_ICD_10_C_M_Code_Cluster,Other_Diagnosis_Code_1_ICD_10_C_M_Cluster,Other_Diagnosis_Code_2_ICD_10_C_M_Cluster,Other_Diagnosis_Code_3_ICD_10_C_M_Cluster,Other_Diagnosis_Code_4_ICD_10_C_M_Cluster,Other_Diagnosis_Code_5_ICD_10_C_M_Cluster,Submitted_HIPPS_Code_1AFK2,Submitted_HIPPS_Code_1AFKS,Submitted_HIPPS_Code_1AFKT,Submitted_HIPPS_Code_1AFKU,Submitted_HIPPS_Code_1AFKV,Submitted_HIPPS_Code_1AFLS,Submitted_HIPPS_Code_1AFLT,Submitted_HIPPS_Code_1AFLU,Submitted_HIPPS_Code_1AFMS,Submitted_HIPPS_Code_1AFMT,Submitted_HIPPS_Code_1AFMU,Submitted_HIPPS_Code_1AFMV,Submitted_HIPPS_Code_1AFNS,Submitted_HIPPS_Code_1AFNT,Submitted_HIPPS_Code_1AFPS,Submitted_HIPPS_Code_1AFPT,Submitted_HIPPS_Code_1AFPU,Submitted_HIPPS_Code_1AGK1,Submitted_HIPPS_Code_1AGKS,Submitted_HIPPS_Code_1AGKT,Submitted_HIPPS_Code_1AGKU,Submitted_HIPPS_Code_1AGKV,Submitted_HIPPS_Code_1AGLS,Submitted_HIPPS_Code_1AGLT,Submitted_HIPPS_Code_1AGLU,Submitted_HIPPS_Code_1AGLV,Submitted_HIPPS_Code_1AGM1,Submitted_HIPPS_Code_1AGMS,Submitted_HIPPS_Code_1AGMT,Submitted_HIPPS_Code_1AGMU,Submitted_HIPPS_Code_1AGMV,Submitted_HIPPS_Code_1AGNS,Submitted_HIPPS_Code_1AGNT,Submitted_HIPPS_Code_1AGNU,Submitted_HIPPS_Code_1AGNV,Submitted_HIPPS_Code_1AGPS,Submitted_HIPPS_Code_1AGPT,Submitted_HIPPS_Code_1AGPU,Submitted_HIPPS_Code_1AGPV,Submitted_HIPPS_Code_1AHK1,Submitted_HIPPS_Code_1AHK2,Submitted_HIPPS_Code_1AHKS,Submitted_HIPPS_Code_1AHKT,Submitted_HIPPS_Code_1AHKU,Submitted_HIPPS_Code_1AHKV,Submitted_HIPPS_Code_1AHKW,Submitted_HIPPS_Code_1AHLS,Submitted_HIPPS_Code_1AHLT,Submitted_HIPPS_Code_1AHLU,Submitted_HIPPS_Code_1AHMS,Submitted_HIPPS_Code_1AHMT,Submitted_HIPPS_Code_1AHMU,Submitted_HIPPS_Code_1AHMV,Submitted_HIPPS_Code_1AHNS,Submitted_HIPPS_Code_1AHNT,Submitted_HIPPS_Code_1AHNU,Submitted_HIPPS_Code_1AHNV,Submitted_HIPPS_Code_1AHNW,Submitted_HIPPS_Code_1AHPS,Submitted_HIPPS_Code_1AHPT,Submitted_HIPPS_Code_1AHPU,Submitted_HIPPS_Code_1AHPV,Submitted_HIPPS_Code_1BFKS,Submitted_HIPPS_Code_1BFKT,Submitted_HIPPS_Code_1BFKU,Submitted_HIPPS_Code_1BFKV,Submitted_HIPPS_Code_1BFLS,Submitted_HIPPS_Code_1BFLT,Submitted_HIPPS_Code_1BFLU,Submitted_HIPPS_Code_1BFLV,Submitted_HIPPS_Code_1BFMS,Submitted_HIPPS_Code_1BFMT,Submitted_HIPPS_Code_1BFMU,Submitted_HIPPS_Code_1BFMV,Submitted_HIPPS_Code_1BFNS,Submitted_HIPPS_Code_1BFNT,Submitted_HIPPS_Code_1BFNU,Submitted_HIPPS_Code_1BFPS,Submitted_HIPPS_Code_1BFPT,Submitted_HIPPS_Code_1BFPU,Submitted_HIPPS_Code_1BFPV,Submitted_HIPPS_Code_1BGK1,Submitted_HIPPS_Code_1BGK2,Submitted_HIPPS_Code_1BGKS,Submitted_HIPPS_Code_1BGKT,Submitted_HIPPS_Code_1BGKU,Submitted_HIPPS_Code_1BGKV,Submitted_HIPPS_Code_1BGKW,Submitted_HIPPS_Code_1BGLS,Submitted_HIPPS_Code_1BGLT,Submitted_HIPPS_Code_1BGLU,Submitted_HIPPS_Code_1BGLV,Submitted_HIPPS_Code_1BGM1,Submitted_HIPPS_Code_1BGMS,Submitted_HIPPS_Code_1BGMT,Submitted_HIPPS_Code_1BGMU,Submitted_HIPPS_Code_1BGMV,Submitted_HIPPS_Code_1BGNS,Submitted_HIPPS_Code_1BGNT,Submitted_HIPPS_Code_1BGNU,Submitted_HIPPS_Code_1BGNV,Submitted_HIPPS_Code_1BGP1,Submitted_HIPPS_Code_1BGPS,Submitted_HIPPS_Code_1BGPT,Submitted_HIPPS_Code_1BGPU,Submitted_HIPPS_Code_1BGPV,Submitted_HIPPS_Code_1BHK1,Submitted_HIPPS_Code_1BHKS,Submitted_HIPPS_Code_1BHKT,Submitted_HIPPS_Code_1BHKU,Submitted_HIPPS_Code_1BHKV,Submitted_HIPPS_Code_1BHKW,Submitted_HIPPS_Code_1BHLS,Submitted_HIPPS_Code_1BHLT,Submitted_HIPPS_Code_1BHLU,Submitted_HIPPS_Code_1BHLV,Submitted_HIPPS_Code_1BHMS,Submitted_HIPPS_Code_1BHMT,Submitted_HIPPS_Code_1BHMU,Submitted_HIPPS_Code_1BHMV,Submitted_HIPPS_Code_1BHN1,Submitted_HIPPS_Code_1BHNS,Submitted_HIPPS_Code_1BHNT,Submitted_HIPPS_Code_1BHNU,Submitted_HIPPS_Code_1BHNV,Submitted_HIPPS_Code_1BHPS,Submitted_HIPPS_Code_1BHPT,Submitted_HIPPS_Code_1BHPU,Submitted_HIPPS_Code_1BHPV,Submitted_HIPPS_Code_1BHPW,Submitted_HIPPS_Code_1CFK1,Submitted_HIPPS_Code_1CFKS,Submitted_HIPPS_Code_1CFKT,Submitted_HIPPS_Code_1CFKU,Submitted_HIPPS_Code_1CFKV,Submitted_HIPPS_Code_1CFKW,Submitted_HIPPS_Code_1CFKX,Submitted_HIPPS_Code_1CFLS,Submitted_HIPPS_Code_1CFLT,Submitted_HIPPS_Code_1CFLU,Submitted_HIPPS_Code_1CFLV,Submitted_HIPPS_Code_1CFLW,Submitted_HIPPS_Code_1CFMS,Submitted_HIPPS_Code_1CFMT,Submitted_HIPPS_Code_1CFMU,Submitted_HIPPS_Code_1CFMV,Submitted_HIPPS_Code_1CFMW,Submitted_HIPPS_Code_1CFNS,Submitted_HIPPS_Code_1CFNT,Submitted_HIPPS_Code_1CFNU,Submitted_HIPPS_Code_1CFNV,Submitted_HIPPS_Code_1CFNW,Submitted_HIPPS_Code_1CFPS,Submitted_HIPPS_Code_1CFPT,Submitted_HIPPS_Code_1CFPU,Submitted_HIPPS_Code_1CFPV,Submitted_HIPPS_Code_1CFPW,Submitted_HIPPS_Code_1CFPX,Submitted_HIPPS_Code_1CGK1,Submitted_HIPPS_Code_1CGKS,Submitted_HIPPS_Code_1CGKT,Submitted_HIPPS_Code_1CGKU,Submitted_HIPPS_Code_1CGKV,Submitted_HIPPS_Code_1CGKW,Submitted_HIPPS_Code_1CGKX,Submitted_HIPPS_Code_1CGL1,Submitted_HIPPS_Code_1CGLS,Submitted_HIPPS_Code_1CGLT,Submitted_HIPPS_Code_1CGLU,Submitted_HIPPS_Code_1CGLV,Submitted_HIPPS_Code_1CGLW,Submitted_HIPPS_Code_1CGMS,Submitted_HIPPS_Code_1CGMT,Submitted_HIPPS_Code_1CGMU,Submitted_HIPPS_Code_1CGMV,Submitted_HIPPS_Code_1CGMW,Submitted_HIPPS_Code_1CGNS,Submitted_HIPPS_Code_1CGNT,Submitted_HIPPS_Code_1CGNU,Submitted_HIPPS_Code_1CGNV,Submitted_HIPPS_Code_1CGNW,Submitted_HIPPS_Code_1CGPS,Submitted_HIPPS_Code_1CGPT,Submitted_HIPPS_Code_1CGPU,Submitted_HIPPS_Code_1CGPV,Submitted_HIPPS_Code_1CGPW,Submitted_HIPPS_Code_1CGPX,Submitted_HIPPS_Code_1CHK1,Submitted_HIPPS_Code_1CHK5,Submitted_HIPPS_Code_1CHKS,Submitted_HIPPS_Code_1CHKT,Submitted_HIPPS_Code_1CHKU,Submitted_HIPPS_Code_1CHKV,Submitted_HIPPS_Code_1CHKW,Submitted_HIPPS_Code_1CHKX,Submitted_HIPPS_Code_1CHLS,Submitted_HIPPS_Code_1CHLT,Submitted_HIPPS_Code_1CHLU,Submitted_HIPPS_Code_1CHLV,Submitted_HIPPS_Code_1CHLW,Submitted_HIPPS_Code_1CHLX,Submitted_HIPPS_Code_1CHM1,Submitted_HIPPS_Code_1CHM3,Submitted_HIPPS_Code_1CHMS,Submitted_HIPPS_Code_1CHMT,Submitted_HIPPS_Code_1CHMU,Submitted_HIPPS_Code_1CHMV,Submitted_HIPPS_Code_1CHMW,Submitted_HIPPS_Code_1CHMX,Submitted_HIPPS_Code_1CHNS,Submitted_HIPPS_Code_1CHNT,Submitted_HIPPS_Code_1CHNU,Submitted_HIPPS_Code_1CHNV,Submitted_HIPPS_Code_1CHNW,Submitted_HIPPS_Code_1CHNX,Submitted_HIPPS_Code_1CHPS,Submitted_HIPPS_Code_1CHPT,Submitted_HIPPS_Code_1CHPU,Submitted_HIPPS_Code_1CHPV,Submitted_HIPPS_Code_1CHPW,Submitted_HIPPS_Code_1CHPX,Submitted_HIPPS_Code_2AFKS,Submitted_HIPPS_Code_2AFKT,Submitted_HIPPS_Code_2AFKU,Submitted_HIPPS_Code_2AFKV,Submitted_HIPPS_Code_2AFLS,Submitted_HIPPS_Code_2AFLT,Submitted_HIPPS_Code_2AFLU,Submitted_HIPPS_Code_2AFMS,Submitted_HIPPS_Code_2AFMT,Submitted_HIPPS_Code_2AFMU,Submitted_HIPPS_Code_2AFMV,Submitted_HIPPS_Code_2AGKS,Submitted_HIPPS_Code_2AGKT,Submitted_HIPPS_Code_2AGKU,Submitted_HIPPS_Code_2AGKV,Submitted_HIPPS_Code_2AGLS,Submitted_HIPPS_Code_2AGLT,Submitted_HIPPS_Code_2AGLU,Submitted_HIPPS_Code_2AGMS,Submitted_HIPPS_Code_2AGMT,Submitted_HIPPS_Code_2AGMU,Submitted_HIPPS_Code_2AHKS,Submitted_HIPPS_Code_2AHKT,Submitted_HIPPS_Code_2AHKU,Submitted_HIPPS_Code_2AHLS,Submitted_HIPPS_Code_2AHLT,Submitted_HIPPS_Code_2AHLU,Submitted_HIPPS_Code_2AHMS,Submitted_HIPPS_Code_2AHMT,Submitted_HIPPS_Code_2AHMU,Submitted_HIPPS_Code_2BFKS,Submitted_HIPPS_Code_2BFKT,Submitted_HIPPS_Code_2BFKU,Submitted_HIPPS_Code_2BFKV,Submitted_HIPPS_Code_2BFLS,Submitted_HIPPS_Code_2BFLT,Submitted_HIPPS_Code_2BFLU,Submitted_HIPPS_Code_2BFLV,Submitted_HIPPS_Code_2BFLW,Submitted_HIPPS_Code_2BFM2,Submitted_HIPPS_Code_2BFMS,Submitted_HIPPS_Code_2BFMT,Submitted_HIPPS_Code_2BFMU,Submitted_HIPPS_Code_2BGKS,Submitted_HIPPS_Code_2BGKT,Submitted_HIPPS_Code_2BGKU,Submitted_HIPPS_Code_2BGKV,Submitted_HIPPS_Code_2BGKW,Submitted_HIPPS_Code_2BGLS,Submitted_HIPPS_Code_2BGLT,Submitted_HIPPS_Code_2BGLU,Submitted_HIPPS_Code_2BGLV,Submitted_HIPPS_Code_2BGMS,Submitted_HIPPS_Code_2BGMT,Submitted_HIPPS_Code_2BGMU,Submitted_HIPPS_Code_2BGMV,Submitted_HIPPS_Code_2BHKS,Submitted_HIPPS_Code_2BHKT,Submitted_HIPPS_Code_2BHKU,Submitted_HIPPS_Code_2BHKV,Submitted_HIPPS_Code_2BHLS,Submitted_HIPPS_Code_2BHLT,Submitted_HIPPS_Code_2BHLU,Submitted_HIPPS_Code_2BHLV,Submitted_HIPPS_Code_2BHMS,Submitted_HIPPS_Code_2BHMT,Submitted_HIPPS_Code_2BHMU,Submitted_HIPPS_Code_2BHMV,Submitted_HIPPS_Code_2CFKS,Submitted_HIPPS_Code_2CFKT,Submitted_HIPPS_Code_2CFKU,Submitted_HIPPS_Code_2CFKV,Submitted_HIPPS_Code_2CFKW,Submitted_HIPPS_Code_2CFKX,Submitted_HIPPS_Code_2CFLS,Submitted_HIPPS_Code_2CFLT,Submitted_HIPPS_Code_2CFLU,Submitted_HIPPS_Code_2CFLV,Submitted_HIPPS_Code_2CFLW,Submitted_HIPPS_Code_2CFLX,Submitted_HIPPS_Code_2CFMS,Submitted_HIPPS_Code_2CFMT,Submitted_HIPPS_Code_2CFMU,Submitted_HIPPS_Code_2CFMV,Submitted_HIPPS_Code_2CFMW,Submitted_HIPPS_Code_2CFMX,Submitted_HIPPS_Code_2CGKS,Submitted_HIPPS_Code_2CGKT,Submitted_HIPPS_Code_2CGKU,Submitted_HIPPS_Code_2CGKV,Submitted_HIPPS_Code_2CGKW,Submitted_HIPPS_Code_2CGKX,Submitted_HIPPS_Code_2CGL1,Submitted_HIPPS_Code_2CGLS,Submitted_HIPPS_Code_2CGLT,Submitted_HIPPS_Code_2CGLU,Submitted_HIPPS_Code_2CGLV,Submitted_HIPPS_Code_2CGLW,Submitted_HIPPS_Code_2CGLX,Submitted_HIPPS_Code_2CGMS,Submitted_HIPPS_Code_2CGMT,Submitted_HIPPS_Code_2CGMU,Submitted_HIPPS_Code_2CGMV,Submitted_HIPPS_Code_2CGMW,Submitted_HIPPS_Code_2CGMX,Submitted_HIPPS_Code_2CHKS,Submitted_HIPPS_Code_2CHKT,Submitted_HIPPS_Code_2CHKU,Submitted_HIPPS_Code_2CHKV,Submitted_HIPPS_Code_2CHKW,Submitted_HIPPS_Code_2CHKX,Submitted_HIPPS_Code_2CHLS,Submitted_HIPPS_Code_2CHLT,Submitted_HIPPS_Code_2CHLU,Submitted_HIPPS_Code_2CHLV,Submitted_HIPPS_Code_2CHLW,Submitted_HIPPS_Code_2CHLX,Submitted_HIPPS_Code_2CHMS,Submitted_HIPPS_Code_2CHMT,Submitted_HIPPS_Code_2CHMU,Submitted_HIPPS_Code_2CHMV,Submitted_HIPPS_Code_2CHMW,Submitted_HIPPS_Code_2CHMX,Submitted_HIPPS_Code_3AFKS,Submitted_HIPPS_Code_3AFKT,Submitted_HIPPS_Code_3AFKU,Submitted_HIPPS_Code_3AFLS,Submitted_HIPPS_Code_3AFMS,Submitted_HIPPS_Code_3AFNS,Submitted_HIPPS_Code_3AFNT,Submitted_HIPPS_Code_3AFPS,Submitted_HIPPS_Code_3AFPT,Submitted_HIPPS_Code_3AGKS,Submitted_HIPPS_Code_3AGKT,Submitted_HIPPS_Code_3AGKU,Submitted_HIPPS_Code_3AGKV,Submitted_HIPPS_Code_3AGLS,Submitted_HIPPS_Code_3AGMS,Submitted_HIPPS_Code_3AGMT,Submitted_HIPPS_Code_3AGMU,Submitted_HIPPS_Code_3AGNS,Submitted_HIPPS_Code_3AGPS,Submitted_HIPPS_Code_3AGPT,Submitted_HIPPS_Code_3AHKS,Submitted_HIPPS_Code_3AHKT,Submitted_HIPPS_Code_3AHKU,Submitted_HIPPS_Code_3AHLS,Submitted_HIPPS_Code_3AHLT,Submitted_HIPPS_Code_3AHMS,Submitted_HIPPS_Code_3AHMT,Submitted_HIPPS_Code_3AHMU,Submitted_HIPPS_Code_3AHNS,Submitted_HIPPS_Code_3AHNT,Submitted_HIPPS_Code_3AHPS,Submitted_HIPPS_Code_3AHPT,Submitted_HIPPS_Code_3AHPU,Submitted_HIPPS_Code_3BFKS,Submitted_HIPPS_Code_3BFKT,Submitted_HIPPS_Code_3BFKU,Submitted_HIPPS_Code_3BFLS,Submitted_HIPPS_Code_3BFMS,Submitted_HIPPS_Code_3BFNS,Submitted_HIPPS_Code_3BFNT,Submitted_HIPPS_Code_3BFPS,Submitted_HIPPS_Code_3BGKS,Submitted_HIPPS_Code_3BGKT,Submitted_HIPPS_Code_3BGKU,Submitted_HIPPS_Code_3BGLS,Submitted_HIPPS_Code_3BGMS,Submitted_HIPPS_Code_3BGMT,Submitted_HIPPS_Code_3BGMU,Submitted_HIPPS_Code_3BGNS,Submitted_HIPPS_Code_3BGPS,Submitted_HIPPS_Code_3BGPT,Submitted_HIPPS_Code_3BGPU,Submitted_HIPPS_Code_3BHKS,Submitted_HIPPS_Code_3BHKT,Submitted_HIPPS_Code_3BHKU,Submitted_HIPPS_Code_3BHKV,Submitted_HIPPS_Code_3BHLS,Submitted_HIPPS_Code_3BHLT,Submitted_HIPPS_Code_3BHMS,Submitted_HIPPS_Code_3BHMT,Submitted_HIPPS_Code_3BHMU,Submitted_HIPPS_Code_3BHNS,Submitted_HIPPS_Code_3BHNT,Submitted_HIPPS_Code_3BHNU,Submitted_HIPPS_Code_3BHNV,Submitted_HIPPS_Code_3BHPS,Submitted_HIPPS_Code_3BHPT,Submitted_HIPPS_Code_3BHPU,Submitted_HIPPS_Code_3CFKS,Submitted_HIPPS_Code_3CFKT,Submitted_HIPPS_Code_3CFKU,Submitted_HIPPS_Code_3CFKV,Submitted_HIPPS_Code_3CFKW,Submitted_HIPPS_Code_3CFKX,Submitted_HIPPS_Code_3CFMT,Submitted_HIPPS_Code_3CFNS,Submitted_HIPPS_Code_3CFNU,Submitted_HIPPS_Code_3CFPS,Submitted_HIPPS_Code_3CFPV,Submitted_HIPPS_Code_3CGK1,Submitted_HIPPS_Code_3CGKS,Submitted_HIPPS_Code_3CGKT,Submitted_HIPPS_Code_3CGKU,Submitted_HIPPS_Code_3CGKV,Submitted_HIPPS_Code_3CGKW,Submitted_HIPPS_Code_3CGLS,Submitted_HIPPS_Code_3CGLT,Submitted_HIPPS_Code_3CGLU,Submitted_HIPPS_Code_3CGLV,Submitted_HIPPS_Code_3CGMS,Submitted_HIPPS_Code_3CGMT,Submitted_HIPPS_Code_3CGMU,Submitted_HIPPS_Code_3CGMV,Submitted_HIPPS_Code_3CGMW,Submitted_HIPPS_Code_3CGNS,Submitted_HIPPS_Code_3CGNT,Submitted_HIPPS_Code_3CGNU,Submitted_HIPPS_Code_3CGNV,Submitted_HIPPS_Code_3CGNW,Submitted_HIPPS_Code_3CGPS,Submitted_HIPPS_Code_3CGPT,Submitted_HIPPS_Code_3CGPU,Submitted_HIPPS_Code_3CGPV,Submitted_HIPPS_Code_3CGPW,Submitted_HIPPS_Code_3CHKS,Submitted_HIPPS_Code_3CHKT,Submitted_HIPPS_Code_3CHKU,Submitted_HIPPS_Code_3CHKV,Submitted_HIPPS_Code_3CHKW,Submitted_HIPPS_Code_3CHKX,Submitted_HIPPS_Code_3CHLS,Submitted_HIPPS_Code_3CHLT,Submitted_HIPPS_Code_3CHLU,Submitted_HIPPS_Code_3CHLV,Submitted_HIPPS_Code_3CHMS,Submitted_HIPPS_Code_3CHMT,Submitted_HIPPS_Code_3CHMU,Submitted_HIPPS_Code_3CHMV,Submitted_HIPPS_Code_3CHMW,Submitted_HIPPS_Code_3CHNS,Submitted_HIPPS_Code_3CHNT,Submitted_HIPPS_Code_3CHNU,Submitted_HIPPS_Code_3CHNV,Submitted_HIPPS_Code_3CHNW,Submitted_HIPPS_Code_3CHPS,Submitted_HIPPS_Code_3CHPT,Submitted_HIPPS_Code_3CHPU,Submitted_HIPPS_Code_3CHPV,Submitted_HIPPS_Code_3CHPW,Submitted_HIPPS_Code_3CHPX,Submitted_HIPPS_Code_4AFKS,Submitted_HIPPS_Code_4AFLS,Submitted_HIPPS_Code_4AFMS,Submitted_HIPPS_Code_4AGKS,Submitted_HIPPS_Code_4AGKT,Submitted_HIPPS_Code_4AGKU,Submitted_HIPPS_Code_4AGLS,Submitted_HIPPS_Code_4AGLT,Submitted_HIPPS_Code_4AGLU,Submitted_HIPPS_Code_4AGMS,Submitted_HIPPS_Code_4AGMT,Submitted_HIPPS_Code_4AHKS,Submitted_HIPPS_Code_4AHKT,Submitted_HIPPS_Code_4AHLS,Submitted_HIPPS_Code_4AHMS,Submitted_HIPPS_Code_4AHMT,Submitted_HIPPS_Code_4BFKS,Submitted_HIPPS_Code_4BFLS,Submitted_HIPPS_Code_4BFLU,Submitted_HIPPS_Code_4BFMS,Submitted_HIPPS_Code_4BGKS,Submitted_HIPPS_Code_4BGKT,Submitted_HIPPS_Code_4BGKU,Submitted_HIPPS_Code_4BGLS,Submitted_HIPPS_Code_4BGLT,Submitted_HIPPS_Code_4BGLU,Submitted_HIPPS_Code_4BGMS,Submitted_HIPPS_Code_4BGMT,Submitted_HIPPS_Code_4BGMU,Submitted_HIPPS_Code_4BGMV,Submitted_HIPPS_Code_4BHKS,Submitted_HIPPS_Code_4BHKT,Submitted_HIPPS_Code_4BHKU,Submitted_HIPPS_Code_4BHLS,Submitted_HIPPS_Code_4BHLT,Submitted_HIPPS_Code_4BHMS,Submitted_HIPPS_Code_4BHMT,Submitted_HIPPS_Code_4BHMU,Submitted_HIPPS_Code_4CFKT,Submitted_HIPPS_Code_4CFLT,Submitted_HIPPS_Code_4CFLV,Submitted_HIPPS_Code_4CGKS,Submitted_HIPPS_Code_4CGKT,Submitted_HIPPS_Code_4CGKU,Submitted_HIPPS_Code_4CGKV,Submitted_HIPPS_Code_4CGKW,Submitted_HIPPS_Code_4CGLS,Submitted_HIPPS_Code_4CGLT,Submitted_HIPPS_Code_4CGLU,Submitted_HIPPS_Code_4CGLV,Submitted_HIPPS_Code_4CGLW,Submitted_HIPPS_Code_4CGMS,Submitted_HIPPS_Code_4CGMT,Submitted_HIPPS_Code_4CGMU,Submitted_HIPPS_Code_4CGMV,Submitted_HIPPS_Code_4CGMW,Submitted_HIPPS_Code_4CHKS,Submitted_HIPPS_Code_4CHKT,Submitted_HIPPS_Code_4CHKU,Submitted_HIPPS_Code_4CHKV,Submitted_HIPPS_Code_4CHKW,Submitted_HIPPS_Code_4CHKX,Submitted_HIPPS_Code_4CHLS,Submitted_HIPPS_Code_4CHLT,Submitted_HIPPS_Code_4CHLU,Submitted_HIPPS_Code_4CHLV,Submitted_HIPPS_Code_4CHLW,Submitted_HIPPS_Code_4CHLX,Submitted_HIPPS_Code_4CHMS,Submitted_HIPPS_Code_4CHMT,Submitted_HIPPS_Code_4CHMU,Submitted_HIPPS_Code_4CHMV,Submitted_HIPPS_Code_4CHMW,Submitted_HIPPS_Code_5AFKS,Submitted_HIPPS_Code_5AFKT,Submitted_HIPPS_Code_5AFKU,Submitted_HIPPS_Code_5AGK1,Submitted_HIPPS_Code_5AGKS,Submitted_HIPPS_Code_5AGKT,Submitted_HIPPS_Code_5AGKU,Submitted_HIPPS_Code_5AHKS,Submitted_HIPPS_Code_5AHKT,Submitted_HIPPS_Code_5AHKU,Submitted_HIPPS_Code_5AHKV,Submitted_HIPPS_Code_5BFKS,Submitted_HIPPS_Code_5BFKT,Submitted_HIPPS_Code_5BFKU,Submitted_HIPPS_Code_5BGKS,Submitted_HIPPS_Code_5BGKT,Submitted_HIPPS_Code_5BGKU,Submitted_HIPPS_Code_5BGKV,Submitted_HIPPS_Code_5BGKW,Submitted_HIPPS_Code_5BHKS,Submitted_HIPPS_Code_5BHKT,Submitted_HIPPS_Code_5BHKU,Submitted_HIPPS_Code_5BHKV,Submitted_HIPPS_Code_5BHKW,Submitted_HIPPS_Code_5CFKS,Submitted_HIPPS_Code_5CFKT,Submitted_HIPPS_Code_5CFKU,Submitted_HIPPS_Code_5CFKV,Submitted_HIPPS_Code_5CFKW,Submitted_HIPPS_Code_5CGKS,Submitted_HIPPS_Code_5CGKT,Submitted_HIPPS_Code_5CGKU,Submitted_HIPPS_Code_5CGKV,Submitted_HIPPS_Code_5CGKW,Submitted_HIPPS_Code_5CGKX,Submitted_HIPPS_Code_5CHKS,Submitted_HIPPS_Code_5CHKT,Submitted_HIPPS_Code_5CHKU,Submitted_HIPPS_Code_5CHKV,Submitted_HIPPS_Code_5CHKW,Submitted_HIPPS_Code_5CHKX,Gender_Male,ByDiscipline_PT,ByDiscipline_RN,ByDiscipline_SLP/ST,BMI_Category_Obese-Class1,BMI_Category_Obese-Class2,BMI_Category_Obese-Class3,BMI_Category_Overweight,BMI_Category_Underweight,COUNTY_NAME_Andrews,COUNTY_NAME_Angelina,COUNTY_NAME_Aransas,COUNTY_NAME_Archer,COUNTY_NAME_Armstrong,COUNTY_NAME_Atascosa,COUNTY_NAME_Austin,COUNTY_NAME_Bailey,COUNTY_NAME_Bandera,COUNTY_NAME_Bastrop,COUNTY_NAME_Baylor,COUNTY_NAME_Bee,COUNTY_NAME_Bell,COUNTY_NAME_Bexar,COUNTY_NAME_Blanco,COUNTY_NAME_Borden,COUNTY_NAME_Bosque,COUNTY_NAME_Bowie,COUNTY_NAME_Brazoria,COUNTY_NAME_Brazos,COUNTY_NAME_Brewster,COUNTY_NAME_Briscoe,COUNTY_NAME_Brooks,COUNTY_NAME_Brown,COUNTY_NAME_Burleson,COUNTY_NAME_Burnet,COUNTY_NAME_Caldwell,COUNTY_NAME_Calhoun,COUNTY_NAME_Callahan,COUNTY_NAME_Cameron,COUNTY_NAME_Camp,COUNTY_NAME_Carson,COUNTY_NAME_Cass,COUNTY_NAME_Castro,COUNTY_NAME_Chambers,COUNTY_NAME_Cherokee,COUNTY_NAME_Childress,COUNTY_NAME_Clay,COUNTY_NAME_Cochran,COUNTY_NAME_Coke,COUNTY_NAME_Coleman,COUNTY_NAME_Collin,COUNTY_NAME_Collingsworth,COUNTY_NAME_Colorado,COUNTY_NAME_Comal,COUNTY_NAME_Comanche,COUNTY_NAME_Concho,COUNTY_NAME_Cooke,COUNTY_NAME_Coryell,COUNTY_NAME_Cottle,COUNTY_NAME_Crane,COUNTY_NAME_Crockett,COUNTY_NAME_Crosby,COUNTY_NAME_Culberson,COUNTY_NAME_Dallam,COUNTY_NAME_Dallas,COUNTY_NAME_Dawson,COUNTY_NAME_DeWitt,COUNTY_NAME_Deaf Smith,COUNTY_NAME_Delta,COUNTY_NAME_Denton,COUNTY_NAME_Dickens,COUNTY_NAME_Dimmit,COUNTY_NAME_Donley,COUNTY_NAME_Duval,COUNTY_NAME_Eastland,COUNTY_NAME_Ector,COUNTY_NAME_Edwards,COUNTY_NAME_El Paso,COUNTY_NAME_Ellis,COUNTY_NAME_Erath,COUNTY_NAME_Falls,COUNTY_NAME_Fannin,COUNTY_NAME_Fayette,COUNTY_NAME_Fisher,COUNTY_NAME_Floyd,COUNTY_NAME_Foard,COUNTY_NAME_Fort Bend,COUNTY_NAME_Franklin,COUNTY_NAME_Freestone,COUNTY_NAME_Frio,COUNTY_NAME_Gaines,COUNTY_NAME_Galveston,COUNTY_NAME_Garza,COUNTY_N

In [42]:
import numpy as np

corr_abs = corr_matrix.abs()

# Choose your threshold (common: 0.8–0.95 depending on aggressiveness)
threshold = 0.8

# Take upper triangle (excluding diagonal)
upper = corr_abs.where(np.triu(np.ones(corr_abs.shape), k=1).astype(bool))

# Columns to drop: any column that has a correlation > threshold with some earlier column
to_drop = [col for col in upper.columns if any(upper[col] > threshold)]

print("Dropping highly correlated columns:", to_drop)

# Create a reduced model dataframe
df_model_reduced = df_model.drop(columns=to_drop)

df_model_reduced

Dropping highly correlated columns: ['charlson_survival_10yr', 'elix_quan_ageadj', 'elix_swiss_score', 'elix_swiss_ageadj', 'POPPCT_RUR', 'ACS_PCT_GRADUATE_DGR', 'ACS_PCT_HS_GRADUATE', 'ACS_PCT_POSTHS_ED', 'ACS_PCT_VET_BACHELOR', 'ACS_PCT_VET_HS', 'ACS_PCT_HH_BROADBAND', 'ACS_PCT_HH_CELLULAR', 'ACS_PCT_HH_INTERNET', 'ACS_PCT_HH_NO_COMP_DEV', 'ACS_PCT_HH_NO_INTERNET', 'ACS_PCT_HH_PC', 'ACS_PCT_HH_SMARTPHONE', 'ACS_PCT_HH_SMARTPHONE_ONLY', 'ACS_PCT_HH_TABLET', 'ACS_PCT_HH_ALONE_ABOVE65', 'ACS_PCT_HH_KID_1PRNT', 'ACS_PCT_HEALTH_INC_ABOVE400', 'ACS_PCT_HEALTH_INC_BELOW137', 'ACS_PCT_HH_1FAM_FOOD_STMP', 'ACS_PCT_HH_FOOD_STMP_BLW_POV', 'ACS_PCT_HH_PUB_ASSIST', 'ACS_PCT_INC50', 'ACS_PCT_NONVET_POV_18_64', 'ACS_PCT_PERSON_INC_100_124', 'ACS_PCT_PERSON_INC_125_199', 'ACS_PCT_PERSON_INC_ABOVE200', 'ACS_PCT_PERSON_INC_BELOW99', 'ACS_PCT_POV_WHITE', 'ByDiscipline_RN']

,Beneficiary_ID,Age,American_Indian_or_Alaska_Native,Asian,Black_or_African_American,Hispanic_or_Latino,Native_Hawiian_or_Pacific_Islander,White,Days_Cared_For,has_diabetes,has_heart_failure,has_hypertension,ever_deceased,ever_readmitted,charlson_score,charlson_ageadj,elix_quan_score,aids,alcohol,ami,canc,carit,cevd,chf,coag,copd,dane,dementia,depre,drug,fed,hp,hypc,hypothy,hypunc,ld,lymph,metacanc,obes,ond,pcd,psycho,pvd,rend,rheumd,valv,wloss,POP_URB,POPPCT_URB,POP_RUR,ACS_PCT_BACHELOR_DGR,ACS_PCT_COLLEGE_ASSOCIATE_DGR,ACS_PCT_LT_HS,ACS_PCT_NO_WORK_NO_SCHL_16_19,ACS_PCT_VET_COLLEGE,ACS_PCT_HH_LIMIT_ENGLISH,ACS_PCT_HH_BROADBAND_ONLY,ACS_PCT_HH_CELLULAR_ONLY,ACS_PCT_HH_DIAL_INTERNET_ONLY,ACS_PCT_HH_INTERNET_NO_SUBS,ACS_PCT_HH_OTHER_COMP,ACS_PCT_HH_OTHER_COMP_ONLY,ACS_PCT_HH_PC_ONLY,ACS_PCT_HH_SAT_INTERNET,ACS_PCT_HH_TABLET_ONLY,ACS_PCT_CHILDREN_GRANDPARENT,ACS_PCT_CHILD_1FAM,ACS_PCT_GRANDP_NO_RESPS,ACS_PCT_GRANDP_RESPS_NO_P,ACS_PCT_GRANDP_RESPS_P,ACS_PCT_HH_1PERS,ACS_PCT_HH_ABOVE65,ACS_TOT_GRANDCHILDREN_GP,ACS_PCT_HEALTH_INC_138_199,ACS_PCT_HEALTH_INC_200_399,ACS_PCT_HH_NO_FD_STMP_BLW_POV,ACS_PCT_INC50_ABOVE65,ACS_PCT_POV_AIAN,ACS_PCT_POV_ASIAN,ACS_PCT_POV_BLACK,ACS_PCT_POV_HISPANIC,ACS_PCT_POV_MULTI,ACS_PCT_POV_NHPI,ACS_PCT_POV_OTHER,ACS_PCT_VET_POV_18_64,ACS_TOT_POP_POV,Facility_Internal_ID,Agency_Medicare_Number,Primary_Diagnosis_ICD_10_C_M_Code_Cluster,Other_Diagnosis_Code_1_ICD_10_C_M_Cluster,Other_Diagnosis_Code_2_ICD_10_C_M_Cluster,Other_Diagnosis_Code_3_ICD_10_C_M_Cluster,Other_Diagnosis_Code_4_ICD_10_C_M_Cluster,Other_Diagnosis_Code_5_ICD_10_C_M_Cluster,Submitted_HIPPS_Code_1AFK2,Submitted_HIPPS_Code_1AFKS,Submitted_HIPPS_Code_1AFKT,Submitted_HIPPS_Code_1AFKU,Submitted_HIPPS_Code_1AFKV,Submitted_HIPPS_Code_1AFLS,Submitted_HIPPS_Code_1AFLT,Submitted_HIPPS_Code_1AFLU,Submitted_HIPPS_Code_1AFMS,Submitted_HIPPS_Code_1AFMT,Submitted_HIPPS_Code_1AFMU,Submitted_HIPPS_Code_1AFMV,Submitted_HIPPS_Code_1AFNS,Submitted_HIPPS_Code_1AFNT,Submitted_HIPPS_Code_1AFPS,Submitted_HIPPS_Code_1AFPT,Submitted_HIPPS_Code_1AFPU,Submitted_HIPPS_Code_1AGK1,Submitted_HIPPS_Code_1AGKS,Submitted_HIPPS_Code_1AGKT,Submitted_HIPPS_Code_1AGKU,Submitted_HIPPS_Code_1AGKV,Submitted_HIPPS_Code_1AGLS,Submitted_HIPPS_Code_1AGLT,Submitted_HIPPS_Code_1AGLU,Submitted_HIPPS_Code_1AGLV,Submitted_HIPPS_Code_1AGM1,Submitted_HIPPS_Code_1AGMS,Submitted_HIPPS_Code_1AGMT,Submitted_HIPPS_Code_1AGMU,Submitted_HIPPS_Code_1AGMV,Submitted_HIPPS_Code_1AGNS,Submitted_HIPPS_Code_1AGNT,Submitted_HIPPS_Code_1AGNU,Submitted_HIPPS_Code_1AGNV,Submitted_HIPPS_Code_1AGPS,Submitted_HIPPS_Code_1AGPT,Submitted_HIPPS_Code_1AGPU,Submitted_HIPPS_Code_1AGPV,Submitted_HIPPS_Code_1AHK1,Submitted_HIPPS_Code_1AHK2,Submitted_HIPPS_Code_1AHKS,Submitted_HIPPS_Code_1AHKT,Submitted_HIPPS_Code_1AHKU,Submitted_HIPPS_Code_1AHKV,Submitted_HIPPS_Code_1AHKW,Submitted_HIPPS_Code_1AHLS,Submitted_HIPPS_Code_1AHLT,Submitted_HIPPS_Code_1AHLU,Submitted_HIPPS_Code_1AHMS,Submitted_HIPPS_Code_1AHMT,Submitted_HIPPS_Code_1AHMU,Submitted_HIPPS_Code_1AHMV,Submitted_HIPPS_Code_1AHNS,Submitted_HIPPS_Code_1AHNT,Submitted_HIPPS_Code_1AHNU,Submitted_HIPPS_Code_1AHNV,Submitted_HIPPS_Code_1AHNW,Submitted_HIPPS_Code_1AHPS,Submitted_HIPPS_Code_1AHPT,Submitted_HIPPS_Code_1AHPU,Submitted_HIPPS_Code_1AHPV,Submitted_HIPPS_Code_1BFKS,Submitted_HIPPS_Code_1BFKT,Submitted_HIPPS_Code_1BFKU,Submitted_HIPPS_Code_1BFKV,Submitted_HIPPS_Code_1BFLS,Submitted_HIPPS_Code_1BFLT,Submitted_HIPPS_Code_1BFLU,Submitted_HIPPS_Code_1BFLV,Submitted_HIPPS_Code_1BFMS,Submitted_HIPPS_Code_1BFMT,Submitted_HIPPS_Code_1BFMU,Submitted_HIPPS_Code_1BFMV,Submitted_HIPPS_Code_1BFNS,Submitted_HIPPS_Code_1BFNT,Submitted_HIPPS_Code_1BFNU,Submitted_HIPPS_Code_1BFPS,Submitted_HIPPS_Code_1BFPT,Submitted_HIPPS_Code_1BFPU,Submitted_HIPPS_Code_1BFPV,Submitted_HIPPS_Code_1BGK1,Submitted_HIPPS_Code_1BGK2,Submitted_HIPPS_Code_1BGKS,Submitted_HIPPS_Code_1BGKT,Submitted_HIPPS_Code_1BGKU,Submitted_HIPPS_Code_1BGKV,Submitted_HIPPS_Code_1BGKW,Submitted_HIPPS_Code_1BGLS,Submitted_HIPPS_Code_1BGLT,Submitted_HIPPS_Code_1BGLU,Submitted_HIPPS_Code_1BGLV,Submitted_HIPPS_Code_1BGM1,Submitted_HIPPS_Code_1BGMS,Submitted_HIPPS_Code_1BGMT,Submitted_HIPPS_Code_1BGMU,Submitted_HIPPS_Code_1BGMV,Submitted_HIPPS_Code_1BGNS,Submitted_HIPPS_Code_1BGNT,Submitted_HIPPS_Code_1BGNU,Submitted_HIPPS_Code_1BGNV,Submitted_HIPPS_Code_1BGP1,Submitted_HIPPS_Code_1BGPS,Submitted_HIPPS_Code_1BGPT,Submitted_HIPPS_Code_1BGPU,Submitted_HIPPS_Code_1BGPV,Submitted_HIPPS_Code_1BHK1,Submitted_HIPPS_Code_1BHKS,Submitted_HIPPS_Code_1BHKT,Submitted_HIPPS_Code_1BHKU,Submitted_HIPPS_Code_1BHKV,Submitted_HIPPS_Code_1BHKW,Submitted_HIPPS_Code_1BHLS,Submitted_HIPPS_Code_1BHLT,Submitted_HIPPS_Code_1BHLU,Submitted_HIPPS_Code_1BHLV,Submitted_HIPPS_Code_1BHMS,Submitted_HIPPS_Code_1BHMT,Submitted_HIPPS_Code_1BHMU,Submitted_HIPPS_Code_1BHMV,Submitted_HIPPS_Code_1BHN1,Submitted_HIPPS_Code_1BHNS,Submitted_HIPPS_Code_1BHNT,Submitted_HIPPS_Code_1BHNU,Submitted_HIPPS_Code_1BHNV,Submitted_HIPPS_Code_1BHPS,Submitted_HIPPS_Code_1BHPT,Submitted_HIPPS_Code_1BHPU,Submitted_HIPPS_Code_1BHPV,Submitted_HIPPS_Code_1BHPW,Submitted_HIPPS_Code_1CFK1,Submitted_HIPPS_Code_1CFKS,Submitted_HIPPS_Code_1CFKT,Submitted_HIPPS_Code_1CFKU,Submitted_HIPPS_Code_1CFKV,Submitted_HIPPS_Code_1CFKW,Submitted_HIPPS_Code_1CFKX,Submitted_HIPPS_Code_1CFLS,Submitted_HIPPS_Code_1CFLT,Submitted_HIPPS_Code_1CFLU,Submitted_HIPPS_Code_1CFLV,Submitted_HIPPS_Code_1CFLW,Submitted_HIPPS_Code_1CFMS,Submitted_HIPPS_Code_1CFMT,Submitted_HIPPS_Code_1CFMU,Submitted_HIPPS_Code_1CFMV,Submitted_HIPPS_Code_1CFMW,Submitted_HIPPS_Code_1CFNS,Submitted_HIPPS_Code_1CFNT,Submitted_HIPPS_Code_1CFNU,Submitted_HIPPS_Code_1CFNV,Submitted_HIPPS_Code_1CFNW,Submitted_HIPPS_Code_1CFPS,Submitted_HIPPS_Code_1CFPT,Submitted_HIPPS_Code_1CFPU,Submitted_HIPPS_Code_1CFPV,Submitted_HIPPS_Code_1CFPW,Submitted_HIPPS_Code_1CFPX,Submitted_HIPPS_Code_1CGK1,Submitted_HIPPS_Code_1CGKS,Submitted_HIPPS_Code_1CGKT,Submitted_HIPPS_Code_1CGKU,Submitted_HIPPS_Code_1CGKV,Submitted_HIPPS_Code_1CGKW,Submitted_HIPPS_Code_1CGKX,Submitted_HIPPS_Code_1CGL1,Submitted_HIPPS_Code_1CGLS,Submitted_HIPPS_Code_1CGLT,Submitted_HIPPS_Code_1CGLU,Submitted_HIPPS_Code_1CGLV,Submitted_HIPPS_Code_1CGLW,Submitted_HIPPS_Code_1CGMS,Submitted_HIPPS_Code_1CGMT,Submitted_HIPPS_Code_1CGMU,Submitted_HIPPS_Code_1CGMV,Submitted_HIPPS_Code_1CGMW,Submitted_HIPPS_Code_1CGNS,Submitted_HIPPS_Code_1CGNT,Submitted_HIPPS_Code_1CGNU,Submitted_HIPPS_Code_1CGNV,Submitted_HIPPS_Code_1CGNW,Submitted_HIPPS_Code_1CGPS,Submitted_HIPPS_Code_1CGPT,Submitted_HIPPS_Code_1CGPU,Submitted_HIPPS_Code_1CGPV,Submitted_HIPPS_Code_1CGPW,Submitted_HIPPS_Code_1CGPX,Submitted_HIPPS_Code_1CHK1,Submitted_HIPPS_Code_1CHK5,Submitted_HIPPS_Code_1CHKS,Submitted_HIPPS_Code_1CHKT,Submitted_HIPPS_Code_1CHKU,Submitted_HIPPS_Code_1CHKV,Submitted_HIPPS_Code_1CHKW,Submitted_HIPPS_Code_1CHKX,Submitted_HIPPS_Code_1CHLS,Submitted_HIPPS_Code_1CHLT,Submitted_HIPPS_Code_1CHLU,Submitted_HIPPS_Code_1CHLV,Submitted_HIPPS_Code_1CHLW,Submitted_HIPPS_Code_1CHLX,Submitted_HIPPS_Code_1CHM1,Submitted_HIPPS_Code_1CHM3,Submitted_HIPPS_Code_1CHMS,Submitted_HIPPS_Code_1CHMT,Submitted_HIPPS_Code_1CHMU,Submitted_HIPPS_Code_1CHMV,Submitted_HIPPS_Code_1CHMW,Submitted_HIPPS_Code_1CHMX,Submitted_HIPPS_Code_1CHNS,Submitted_HIPPS_Code_1CHNT,Submitted_HIPPS_Code_1CHNU,Submitted_HIPPS_Code_1CHNV,Submitted_HIPPS_Code_1CHNW,Submitted_HIPPS_Code_1CHNX,Submitted_HIPPS_Code_1CHPS,Submitted_HIPPS_Code_1CHPT,Submitted_HIPPS_Code_1CHPU,Submitted_HIPPS_Code_1CHPV,Submitted_HIPPS_Code_1CHPW,Submitted_HIPPS_Code_1CHPX,Submitted_HIPPS_Code_2AFKS,Submitted_HIPPS_Code_2AFKT,Submitted_HIPPS_Code_2AFKU,Submitted_HIPPS_Code_2AFKV,Submitted_HIPPS_Code_2AFLS,Submitted_HIPPS_Code_2AFLT,Submitted_HIPPS_Code_2AFLU,Submitted_HIPPS_Code_2AFMS,Submitted_HIPPS_Code_2AFMT,Submitted_HIPPS_Code_2AFMU,Submitted_HIPPS_Code_2AFMV,Submitted_HIPPS_Code_2AGKS,Submitted_HIPPS_Code_2AGKT,Submitted_HIPPS_Code_2AGKU,Submitted_HIPPS_Code_2AGKV,Submitted_HIPPS_Code_2AGLS,Submitted_HIPPS_Code_2AGLT,Submitted_HIPPS_Code_2AGLU,Submitted_HIPPS_Code_2AGMS,Submitted_HIPPS_Code_2AGMT,Submitted_HIPPS_Code_2AGMU,Submitted_HIPPS_Code_2AHKS,Submitted_HIPPS_Code_2AHKT,Submitted_HIPPS_Code_2AHKU,Submitted_HIPPS_Code_2AHLS,Submitted_HIPPS_Code_2AHLT,Submitted_HIPPS_Code_2AHLU,Submitted_HIPPS_Code_2AHMS,Submitted_HIPPS_Code_2AHMT,Submitted_HIPPS_Code_2AHMU,Submitted_HIPPS_Code_2BFKS,Submitted_HIPPS_Code_2BFKT,Submitted_HIPPS_Code_2BFKU,Submitted_HIPPS_Code_2BFKV,Submitted_HIPPS_Code_2BFLS,Submitted_HIPPS_Code_2BFLT,Submitted_HIPPS_Code_2BFLU,Submitted_HIPPS_Code_2BFLV,Submitted_HIPPS_Code_2BFLW,Submitted_HIPPS_Code_2BFM2,Submitted_HIPPS_Code_2BFMS,Submitted_HIPPS_Code_2BFMT,Submitted_HIPPS_Code_2BFMU,Submitted_HIPPS_Code_2BGKS,Submitted_HIPPS_Code_2BGKT,Submitted_HIPPS_Code_2BGKU,Submitted_HIPPS_Code_2BGKV,Submitted_HIPPS_Code_2BGKW,Submitted_HIPPS_Code_2BGLS,Submitted_HIPPS_Code_2BGLT,Submitted_HIPPS_Code_2BGLU,Submitted_HIPPS_Code_2BGLV,Submitted_HIPPS_Code_2BGMS,Submitted_HIPPS_Code_2BGMT,Submitted_HIPPS_Code_2BGMU,Submitted_HIPPS_Code_2BGMV,Submitted_HIPPS_Code_2BHKS,Submitted_HIPPS_Code_2BHKT,Submitted_HIPPS_Code_2BHKU,Submitted_HIPPS_Code_2BHKV,Submitted_HIPPS_Code_2BHLS,Submitted_HIPPS_Code_2BHLT,Submitted_HIPPS_Code_2BHLU,Submitted_HIPPS_Code_2BHLV,Submitted_HIPPS_Code_2BHMS,Submitted_HIPPS_Code_2BHMT,Submitted_HIPPS_Code_2BHMU,Submitted_HIPPS_Code_2BHMV,Submitted_HIPPS_Code_2CFKS,Submitted_HIPPS_Code_2CFKT,Submitted_HIPPS_Code_2CFKU,Submitted_HIPPS_Code_2CFKV,Submitted_HIPPS_Code_2CFKW,Submitted_HIPPS_Code_2CFKX,Submitted_HIPPS_Code_2CFLS,Submitted_HIPPS_Code_2CFLT,Submitted_HIPPS_Code_2CFLU,Submitted_HIPPS_Code_2CFLV,Submitted_HIPPS_Code_2CFLW,Submitted_HIPPS_Code_2CFLX,Submitted_HIPPS_Code_2CFMS,Submitted_HIPPS_Code_2CFMT,Submitted_HIPPS_Code_2CFMU,Submitted_HIPPS_Code_2CFMV,Submitted_HIPPS_Code_2CFMW,Submitted_HIPPS_Code_2CFMX,Submitted_HIPPS_Code_2CGKS,Submitted_HIPPS_Code_2CGKT,Submitted_HIPPS_Code_2CGKU,Submitted_HIPPS_Code_2CGKV,Submitted_HIPPS_Code_2CGKW,Submitted_HIPPS_Code_2CGKX,Submitted_HIPPS_Code_2CGL1,Submitted_HIPPS_Code_2CGLS,Submitted_HIPPS_Code_2CGLT,Submitted_HIPPS_Code_2CGLU,Submitted_HIPPS_Code_2CGLV,Submitted_HIPPS_Code_2CGLW,Submitted_HIPPS_Code_2CGLX,Submitted_HIPPS_Code_2CGMS,Submitted_HIPPS_Code_2CGMT,Submitted_HIPPS_Code_2CGMU,Submitted_HIPPS_Code_2CGMV,Submitted_HIPPS_Code_2CGMW,Submitted_HIPPS_Code_2CGMX,Submitted_HIPPS_Code_2CHKS,Submitted_HIPPS_Code_2CHKT,Submitted_HIPPS_Code_2CHKU,Submitted_HIPPS_Code_2CHKV,Submitted_HIPPS_Code_2CHKW,Submitted_HIPPS_Code_2CHKX,Submitted_HIPPS_Code_2CHLS,Submitted_HIPPS_Code_2CHLT,Submitted_HIPPS_Code_2CHLU,Submitted_HIPPS_Code_2CHLV,Submitted_HIPPS_Code_2CHLW,Submitted_HIPPS_Code_2CHLX,Submitted_HIPPS_Code_2CHMS,Submitted_HIPPS_Code_2CHMT,Submitted_HIPPS_Code_2CHMU,Submitted_HIPPS_Code_2CHMV,Submitted_HIPPS_Code_2CHMW,Submitted_HIPPS_Code_2CHMX,Submitted_HIPPS_Code_3AFKS,Submitted_HIPPS_Code_3AFKT,Submitted_HIPPS_Code_3AFKU,Submitted_HIPPS_Code_3AFLS,Submitted_HIPPS_Code_3AFMS,Submitted_HIPPS_Code_3AFNS,Submitted_HIPPS_Code_3AFNT,Submitted_HIPPS_Code_3AFPS,Submitted_HIPPS_Code_3AFPT,Submitted_HIPPS_Code_3AGKS,Submitted_HIPPS_Code_3AGKT,Submitted_HIPPS_Code_3AGKU,Submitted_HIPPS_Code_3AGKV,Submitted_HIPPS_Code_3AGLS,Submitted_HIPPS_Code_3AGMS,Submitted_HIPPS_Code_3AGMT,Submitted_HIPPS_Code_3AGMU,Submitted_HIPPS_Code_3AGNS,Submitted_HIPPS_Code_3AGPS,Submitted_HIPPS_Code_3AGPT,Submitted_HIPPS_Code_3AHKS,Submitted_HIPPS_Code_3AHKT,Submitted_HIPPS_Code_3AHKU,Submitted_HIPPS_Code_3AHLS,Submitted_HIPPS_Code_3AHLT,Submitted_HIPPS_Code_3AHMS,Submitted_HIPPS_Code_3AHMT,Submitted_HIPPS_Code_3AHMU,Submitted_HIPPS_Code_3AHNS,Submitted_HIPPS_Code_3AHNT,Submitted_HIPPS_Code_3AHPS,Submitted_HIPPS_Code_3AHPT,Submitted_HIPPS_Code_3AHPU,Submitted_HIPPS_Code_3BFKS,Submitted_HIPPS_Code_3BFKT,Submitted_HIPPS_Code_3BFKU,Submitted_HIPPS_Code_3BFLS,Submitted_HIPPS_Code_3BFMS,Submitted_HIPPS_Code_3BFNS,Submitted_HIPPS_Code_3BFNT,Submitted_HIPPS_Code_3BFPS,Submitted_HIPPS_Code_3BGKS,Submitted_HIPPS_Code_3BGKT,Submitted_HIPPS_Code_3BGKU,Submitted_HIPPS_Code_3BGLS,Submitted_HIPPS_Code_3BGMS,Submitted_HIPPS_Code_3BGMT,Submitted_HIPPS_Code_3BGMU,Submitted_HIPPS_Code_3BGNS,Submitted_HIPPS_Code_3BGPS,Submitted_HIPPS_Code_3BGPT,Submitted_HIPPS_Code_3BGPU,Submitted_HIPPS_Code_3BHKS,Submitted_HIPPS_Code_3BHKT,Submitted_HIPPS_Code_3BHKU,Submitted_HIPPS_Code_3BHKV,Submitted_HIPPS_Code_3BHLS,Submitted_HIPPS_Code_3BHLT,Submitted_HIPPS_Code_3BHMS,Submitted_HIPPS_Code_3BHMT,Submitted_HIPPS_Code_3BHMU,Submitted_HIPPS_Code_3BHNS,Submitted_HIPPS_Code_3BHNT,Submitted_HIPPS_Code_3BHNU,Submitted_HIPPS_Code_3BHNV,Submitted_HIPPS_Code_3BHPS,Submitted_HIPPS_Code_3BHPT,Submitted_HIPPS_Code_3BHPU,Submitted_HIPPS_Code_3CFKS,Submitted_HIPPS_Code_3CFKT,Submitted_HIPPS_Code_3CFKU,Submitted_HIPPS_Code_3CFKV,Submitted_HIPPS_Code_3CFKW,Submitted_HIPPS_Code_3CFKX,Submitted_HIPPS_Code_3CFMT,Submitted_HIPPS_Code_3CFNS,Submitted_HIPPS_Code_3CFNU,Submitted_HIPPS_Code_3CFPS,Submitted_HIPPS_Code_3CFPV,Submitted_HIPPS_Code_3CGK1,Submitted_HIPPS_Code_3CGKS,Submitted_HIPPS_Code_3CGKT,Submitted_HIPPS_Code_3CGKU,Submitted_HIPPS_Code_3CGKV,Submitted_HIPPS_Code_3CGKW,Submitted_HIPPS_Code_3CGLS,Submitted_HIPPS_Code_3CGLT,Submitted_HIPPS_Code_3CGLU,Submitted_HIPPS_Code_3CGLV,Submitted_HIPPS_Code_3CGMS,Submitted_HIPPS_Code_3CGMT,Submitted_HIPPS_Code_3CGMU,Submitted_HIPPS_Code_3CGMV,Submitted_HIPPS_Code_3CGMW,Submitted_HIPPS_Code_3CGNS,Submitted_HIPPS_Code_3CGNT,Submitted_HIPPS_Code_3CGNU,Submitted_HIPPS_Code_3CGNV,Submitted_HIPPS_Code_3CGNW,Submitted_HIPPS_Code_3CGPS,Submitted_HIPPS_Code_3CGPT,Submitted_HIPPS_Code_3CGPU,Submitted_HIPPS_Code_3CGPV,Submitted_HIPPS_Code_3CGPW,Submitted_HIPPS_Code_3CHKS,Submitted_HIPPS_Code_3CHKT,Submitted_HIPPS_Code_3CHKU,Submitted_HIPPS_Code_3CHKV,Submitted_HIPPS_Code_3CHKW,Submitted_HIPPS_Code_3CHKX,Submitted_HIPPS_Code_3CHLS,Submitted_HIPPS_Code_3CHLT,Submitted_HIPPS_Code_3CHLU,Submitted_HIPPS_Code_3CHLV,Submitted_HIPPS_Code_3CHMS,Submitted_HIPPS_Code_3CHMT,Submitted_HIPPS_Code_3CHMU,Submitted_HIPPS_Code_3CHMV,Submitted_HIPPS_Code_3CHMW,Submitted_HIPPS_Code_3CHNS,Submitted_HIPPS_Code_3CHNT,Submitted_HIPPS_Code_3CHNU,Submitted_HIPPS_Code_3CHNV,Submitted_HIPPS_Code_3CHNW,Submitted_HIPPS_Code_3CHPS,Submitted_HIPPS_Code_3CHPT,Submitted_HIPPS_Code_3CHPU,Submitted_HIPPS_Code_3CHPV,Submitted_HIPPS_Code_3CHPW,Submitted_HIPPS_Code_3CHPX,Submitted_HIPPS_Code_4AFKS,Submitted_HIPPS_Code_4AFLS,Submitted_HIPPS_Code_4AFMS,Submitted_HIPPS_Code_4AGKS,Submitted_HIPPS_Code_4AGKT,Submitted_HIPPS_Code_4AGKU,Submitted_HIPPS_Code_4AGLS,Submitted_HIPPS_Code_4AGLT,Submitted_HIPPS_Code_4AGLU,Submitted_HIPPS_Code_4AGMS,Submitted_HIPPS_Code_4AGMT,Submitted_HIPPS_Code_4AHKS,Submitted_HIPPS_Code_4AHKT,Submitted_HIPPS_Code_4AHLS,Submitted_HIPPS_Code_4AHMS,Submitted_HIPPS_Code_4AHMT,Submitted_HIPPS_Code_4BFKS,Submitted_HIPPS_Code_4BFLS,Submitted_HIPPS_Code_4BFLU,Submitted_HIPPS_Code_4BFMS,Submitted_HIPPS_Code_4BGKS,Submitted_HIPPS_Code_4BGKT,Submitted_HIPPS_Code_4BGKU,Submitted_HIPPS_Code_4BGLS,Submitted_HIPPS_Code_4BGLT,Submitted_HIPPS_Code_4BGLU,Submitted_HIPPS_Code_4BGMS,Submitted_HIPPS_Code_4BGMT,Submitted_HIPPS_Code_4BGMU,Submitted_HIPPS_Code_4BGMV,Submitted_HIPPS_Code_4BHKS,Submitted_HIPPS_Code_4BHKT,Submitted_HIPPS_Code_4BHKU,Submitted_HIPPS_Code_4BHLS,Submitted_HIPPS_Code_4BHLT,Submitted_HIPPS_Code_4BHMS,Submitted_HIPPS_Code_4BHMT,Submitted_HIPPS_Code_4BHMU,Submitted_HIPPS_Code_4CFKT,Submitted_HIPPS_Code_4CFLT,Submitted_HIPPS_Code_4CFLV,Submitted_HIPPS_Code_4CGKS,Submitted_HIPPS_Code_4CGKT,Submitted_HIPPS_Code_4CGKU,Submitted_HIPPS_Code_4CGKV,Submitted_HIPPS_Code_4CGKW,Submitted_HIPPS_Code_4CGLS,Submitted_HIPPS_Code_4CGLT,Submitted_HIPPS_Code_4CGLU,Submitted_HIPPS_Code_4CGLV,Submitted_HIPPS_Code_4CGLW,Submitted_HIPPS_Code_4CGMS,Submitted_HIPPS_Code_4CGMT,Submitted_HIPPS_Code_4CGMU,Submitted_HIPPS_Code_4CGMV,Submitted_HIPPS_Code_4CGMW,Submitted_HIPPS_Code_4CHKS,Submitted_HIPPS_Code_4CHKT,Submitted_HIPPS_Code_4CHKU,Submitted_HIPPS_Code_4CHKV,Submitted_HIPPS_Code_4CHKW,Submitted_HIPPS_Code_4CHKX,Submitted_HIPPS_Code_4CHLS,Submitted_HIPPS_Code_4CHLT,Submitted_HIPPS_Code_4CHLU,Submitted_HIPPS_Code_4CHLV,Submitted_HIPPS_Code_4CHLW,Submitted_HIPPS_Code_4CHLX,Submitted_HIPPS_Code_4CHMS,Submitted_HIPPS_Code_4CHMT,Submitted_HIPPS_Code_4CHMU,Submitted_HIPPS_Code_4CHMV,Submitted_HIPPS_Code_4CHMW,Submitted_HIPPS_Code_5AFKS,Submitted_HIPPS_Code_5AFKT,Submitted_HIPPS_Code_5AFKU,Submitted_HIPPS_Code_5AGK1,Submitted_HIPPS_Code_5AGKS,Submitted_HIPPS_Code_5AGKT,Submitted_HIPPS_Code_5AGKU,Submitted_HIPPS_Code_5AHKS,Submitted_HIPPS_Code_5AHKT,Submitted_HIPPS_Code_5AHKU,Submitted_HIPPS_Code_5AHKV,Submitted_HIPPS_Code_5BFKS,Submitted_HIPPS_Code_5BFKT,Submitted_HIPPS_Code_5BFKU,Submitted_HIPPS_Code_5BGKS,Submitted_HIPPS_Code_5BGKT,Submitted_HIPPS_Code_5BGKU,Submitted_HIPPS_Code_5BGKV,Submitted_HIPPS_Code_5BGKW,Submitted_HIPPS_Code_5BHKS,Submitted_HIPPS_Code_5BHKT,Submitted_HIPPS_Code_5BHKU,Submitted_HIPPS_Code_5BHKV,Submitted_HIPPS_Code_5BHKW,Submitted_HIPPS_Code_5CFKS,Submitted_HIPPS_Code_5CFKT,Submitted_HIPPS_Code_5CFKU,Submitted_HIPPS_Code_5CFKV,Submitted_HIPPS_Code_5CFKW,Submitted_HIPPS_Code_5CGKS,Submitted_HIPPS_Code_5CGKT,Submitted_HIPPS_Code_5CGKU,Submitted_HIPPS_Code_5CGKV,Submitted_HIPPS_Code_5CGKW,Submitted_HIPPS_Code_5CGKX,Submitted_HIPPS_Code_5CHKS,Submitted_HIPPS_Code_5CHKT,Submitted_HIPPS_Code_5CHKU,Submitted_HIPPS_Code_5CHKV,Submitted_HIPPS_Code_5CHKW,Submitted_HIPPS_Code_5CHKX,Gender_Male,ByDiscipline_PT,ByDiscipline_SLP/ST,BMI_Category_Obese-Class1,BMI_Category_Obese-Class2,BMI_Category_Obese-Class3,BMI_Category_Overweight,BMI_Category_Underweight,COUNTY_NAME_Andrews,COUNTY_NAME_Angelina,COUNTY_NAME_Aransas,COUNTY_NAME_Archer,COUNTY_NAME_Armstrong,COUNTY_NAME_Atascosa,COUNTY_NAME_Austin,COUNTY_NAME_Bailey,COUNTY_NAME_Bandera,COUNTY_NAME_Bastrop,COUNTY_NAME_Baylor,COUNTY_NAME_Bee,COUNTY_NAME_Bell,COUNTY_NAME_Bexar,COUNTY_NAME_Blanco,COUNTY_NAME_Borden,COUNTY_NAME_Bosque,COUNTY_NAME_Bowie,COUNTY_NAME_Brazoria,COUNTY_NAME_Brazos,COUNTY_NAME_Brewster,COUNTY_NAME_Briscoe,COUNTY_NAME_Brooks,COUNTY_NAME_Brown,COUNTY_NAME_Burleson,COUNTY_NAME_Burnet,COUNTY_NAME_Caldwell,COUNTY_NAME_Calhoun,COUNTY_NAME_Callahan,COUNTY_NAME_Cameron,COUNTY_NAME_Camp,COUNTY_NAME_Carson,COUNTY_NAME_Cass,COUNTY_NAME_Castro,COUNTY_NAME_Chambers,COUNTY_NAME_Cherokee,COUNTY_NAME_Childress,COUNTY_NAME_Clay,COUNTY_NAME_Cochran,COUNTY_NAME_Coke,COUNTY_NAME_Coleman,COUNTY_NAME_Collin,COUNTY_NAME_Collingsworth,COUNTY_NAME_Colorado,COUNTY_NAME_Comal,COUNTY_NAME_Comanche,COUNTY_NAME_Concho,COUNTY_NAME_Cooke,COUNTY_NAME_Coryell,COUNTY_NAME_Cottle,COUNTY_NAME_Crane,COUNTY_NAME_Crockett,COUNTY_NAME_Crosby,COUNTY_NAME_Culberson,COUNTY_NAME_Dallam,COUNTY_NAME_Dallas,COUNTY_NAME_Dawson,COUNTY_NAME_DeWitt,COUNTY_NAME_Deaf Smith,COUNTY_NAME_Delta,COUNTY_NAME_Denton,COUNTY_NAME_Dickens,COUNTY_NAME_Dimmit,COUNTY_NAME_Donley,COUNTY_NAME_Duval,COUNTY_NAME_Eastland,COUNTY_NAME_Ector,COUNTY_NAME_Edwards,COUNTY_NAME_El Paso,COUNTY_NAME_Ellis,COUNTY_NAME_Erath,COUNTY_NAME_Falls,COUNTY_NAME_Fannin,COUNTY_NAME_Fayette,COUNTY_NAME_Fisher,COUNTY_NAME_Floyd,COUNTY_NAME_Foard,COUNTY_NAME_Fort Bend,COUNTY_NAME_Franklin,COUNTY_NAME_Freestone,COUNTY_NAME_Frio,COUNTY_NAME_Gaines,COUNTY_NAME_Galveston,COUNTY_NAME_Garza,COUNTY_NAME_Gillespie,COUNTY_NAME_Glasscock,COUNTY_NAME_Goliad,COUNTY_NAME_Gonzales,COUNTY_NAME_Gray,COUNTY_NAME_Grayson,COUNTY_NAME_Gregg,COUNTY_NAME_Grimes,COUNTY_NAME_Guadalupe,COUNTY_NAME_Hale,COUNTY_NAME_Hall,COUNTY_NAME_Hamilton,COUNTY_NAME_Hansford,COUNTY_NAME_Hardeman,COUNTY_NAME_Hardin,COUNTY_NAME_Harris,COUNTY_NAME_Harrison,COUNTY_NAME_Hartley,COUNTY_NAME_Haskell,COUNTY_NAME_Hays,COUNTY_NAME_Hemphill,COUNTY_NAME_Henderson,COUNTY_NAME_Hidalgo,COUNTY_NAME_Hill,COUNTY_NAME_Hockley,COUNTY_NAME_Hood,COUNTY_NAME_Hopkins,COUNTY_NAME_Houston,COUNTY_NAME_Howard,COUNTY_NAME_Hudspeth,COUNTY_NAME_Hunt,COUNTY_NAME_Hutchinson,COUNTY_NAME_Irion,COUNTY_NAME_Jack,COUNTY_NAME_Jackson,COUNTY_NAME_Jasper,COUNTY_NAME_Jeff Da

In [43]:
df_model_reduced.to_csv('data/processed_final_mergedDF_TX.csv', index=False)